### ISSUE TITLE
How to generate apatch

### ISSUE THREAD

**Issue by hmz17** [alibaba/AndFix#11]
Can anyone please show a working example to generate apatch file in windows. 

It is giving me this error

C:\Users\Hamza Mirza\AndroidStudioProjects\apkpatch>apkpatch -f 2.apk -t 1.apk -
a mykey -e mykey  -p mykey -k C:\Users\Hamza Mirza\AndroidStudioProject
s\apkpatch
Exception in thread "main" java.lang.IllegalArgumentException:  does not exist
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1637)
        at com.euler.patch.Build.<init>(Build.java:50)
        at com.euler.patch.ApkPatch.<init>(ApkPatch.java:40)
        at com.euler.patch.Main.main(Main.java:95)

C:\Users\Hamza Mirza\AndroidStudioProjects\apkpatch>

**Comment by supern** [comment]
-o out

**Comment by MrFuFuFu** [comment]
In the OS X, I was run this command. I hope this can help you.

```
./apkpatch.sh -f 2.apk -t 1.apk -o  /Users/MrFu/Documents/Git/AndFix/samples/AndFixDemo/apk/a -k /Users/MrFu/.android/debug.keystore -p android -a androiddebugkey -e android
```

**Comment by hmz17** [comment]
Thanks MrFuFuFu
Thats going ahead, but now i am getting this error

C:\Users\Hamza Mirza\AndroidStudioProjects\AndFixDemo\app\build\outputs\apk>apkp
atch -f 2.apk -t 1.apk -o  /a -k C:\Users\Hamza Mirza\.android\debug.keystore -p
 android -a androiddebugkey -e android
add modified Method:V  onCreate(Landroid/os/Bundle;)  in Class:Lcom/euler/andfix
/MainActivity;
java.io.FileNotFoundException: C:\Users\Hamza (The system cannot find the file s
pecified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.euler.patch.Build.build(Build.java:76)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:57)
        at com.euler.patch.Main.main(Main.java:97)

**Comment by MrFuFuFu** [comment]
Maybe your users name Hamza Mirza has a space, take out the debug.keystore to the desktop try it again.

`C:\Users\Hamza Mirza.android\debug.keystore`

**Comment by hmz17** [comment]
Thank You so much. Working fine now :)
Yes the problem was with space. fixed it.

Awesome tool.

**Comment by MrFuFuFu** [comment]
@hmz17 nice

**Comment by MrFuFuFu** [comment]
@hmz17 Could you help me to see that how about your out.apatch file size? I generate apatch size only 3KB, but the @supern tell me that should 20KB. 
And now it can't to work.

**Comment by hmz17** [comment]
My output file is 2.94KB, and it's working fine.
