### ISSUE TITLE
回调中修改，也会出问题，报错如下

### ISSUE THREAD

**Issue by yunair** [alibaba/AndFix#110]
java.lang.NoSuchFieldError: No instance field apZ of type Ljava/lang/Object; in class Lcom/*/b/bs; or its superclasses (declaration of 'com.*.b.bs' appears in /data/app/com.*/base.apk)
                                                       at com.*.activity.cb_CF.onSuccess(x.java:93)
                                                       at com.*.b.f.onSuccess(AbstractRestClient.java:241)
                                                       at com.loopj.android.http.JsonHttpResponseHandler$1$1.run(JsonHttpResponseHandler.java:126)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:145)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6872)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by TangHuaiZhe** [comment]
同样出现了这个问题，匿名回调会报NoSuchFieldError错误。
