### ISSUE TITLE
couldn't run on ART

### ISSUE THREAD

**Issue by JackCho** [alibaba/AndFix#119]
I test on 5.0 and 6.0, same error turn up。Meanwhile on 4.x phones it runs normal

below is the log
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/euler/test/Fix_CF;
                                                               at com.euler.andfix.MainActivity_CF.onCreate(Unknown Source)
                                                               at android.app.Activity.performCreate(Activity.java:6237)
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:148)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "com.euler.test.Fix_CF" on path: DexPathList[[zip file "/data/app/ele.me.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/ele.me.demo-1/lib/x86, /data/app/ele.me.demo-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                               at com.euler.andfix.MainActivity_CF.onCreate(Unknown Source) 
                                                               at android.app.Activity.performCreate(Activity.java:6237) 
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:148) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                           	Suppressed: java.lang.ClassNotFoundException: com.euler.test.Fix_CF
                                                               at java.lang.Class.classForName(Native Method)
                                                               at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                               at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                               		... 14 more
                                                            Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by zhonghanwen** [comment]
你的错误好像是x86下找不到对应的so库文件吧~
