### ISSUE TITLE
混淆后 patchManager.loadPatch();处崩溃

### ISSUE THREAD

**Issue by happycodinggirl** [alibaba/AndFix#123]
01-21 16:57:38.295  20350-20350/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: cn.plu.testhotfix, PID: 20350
    java.lang.RuntimeException: Unable to create application cn.plu.testhotfix.AndFixApplication: java.lang.RuntimeException: failure in processEncodedAnnotation
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4616)
            at android.app.ActivityThread.access$1800(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5314)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: failure in processEncodedAnnotation
            at java.lang.reflect.Method.getAnnotation(Native Method)
            at java.lang.reflect.Method.getAnnotation(Method.java:266)
            at com.alipay.euler.andfix.a.a(AndFixManager.java:199)
            at com.alipay.euler.andfix.a.a(AndFixManager.java:179)
            at com.alipay.euler.andfix.a.b.a(PatchManager.java:214)
            at cn.plu.testhotfix.AndFixApplication.onCreate(AndFixApplication.java:26)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1009)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4613)
            at android.app.ActivityThread.access$1800(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5314)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
            at dalvik.system.NativeStart.main(Native Method)
01-21 16:57:38.295    3034-3400/? W/ActivityManager﹕ Force finishing activity cn.plu.testhotfix/.MainActivity

**Comment by happycodinggirl** [comment]
该动的地方时MainActivity 的onCreate 里面的方法

**Comment by JackCho** [comment]
@happycodinggirl please don't minify AndFix library

**Comment by ContinueCoding** [comment]
@happycodinggirl 你这问题解决了吗？能分享一下如何解决的吗？谢谢！

**Comment by happycodinggirl** [comment]
please don't minify AndFix library, it solved my question
