### ISSUE TITLE
 can,t add new Field:val

### ISSUE THREAD

**Issue by ghalong** [alibaba/AndFix#125]
我的class文件中有如下两个方法
@Override
    public void error(final String msg) {
        handler_.post(new Runnable() {

            @Override
            public void run() {
                AboutMeiCaiActivity_.super.error(msg);
            }

        }
        );
    }
@Override
    public void showShortToast(final String text) {
        handler_.post(new Runnable() {

            @Override
            public void run() {
                AboutMeiCaiActivity_.super.showShortToast(text);
            }

        }
        );
    }

然后当我用工具生成patch文件的时候，工具一直报如下的异常
java.lang.RuntimeException: can,t add new Field:val$text(Ljava/lang/String;), in class :Lcom/meicai/mall/activity/AboutMeiCaiActivity_$10;
	at com.euler.patch.diff.DiffInfo.addAddedFields(DiffInfo.java:77)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:132)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:101)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:95)
	at com.euler.patch.diff.DexDiffer.diff(DexDiffer.java:32)
	at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:68)
	at com.euler.patch.Main.main(Main.java:97)
当我把新包旧包调换顺序之后使用那个工具，又报如下异常
add new Method:V  <init>(Lcom/meicai/mall/activity/AboutMeiCaiActivity_;)  in Class:Lcom/meicai/mall/activity/AboutMeiCaiActivity_$10;
add modified Method:V  run()  in Class:Lcom/meicai/mall/activity/AboutMeiCaiActivity_$10;
java.lang.RuntimeException: can,t add new Field:val$msg(Ljava/lang/String;), in class :Lcom/meicai/mall/activity/AboutMeiCaiActivity_$11;
	at com.euler.patch.diff.DiffInfo.addAddedFields(DiffInfo.java:77)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:132)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:101)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:95)
	at com.euler.patch.diff.DexDiffer.diff(DexDiffer.java:32)
	at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:68)
	at com.euler.patch.Main.main(Main.java:97)

事实上那个文件一直都是保持不变的，不明白为什么会一直出现上述问题

**Comment by croccio** [comment]
how do you solved?
