### ISSUE TITLE
java.lang.RuntimeException: can,t modified Field:VERSION_NAME(Ljava/lang/String;), in class :Lcom/zxx/andfixdemo/BuildConfig;

### ISSUE THREAD

**Issue by hush881025** [alibaba/AndFix#129]
脚本命令有问题
使用:apkpatch.bat -f af2.apk -t af1.apk -o output1 -k andfix.keystore  -p abc123 -a zxx -e abc123

报错:
java.lang.RuntimeException: can,t modified Field:VERSION_NAME(Ljava/lang/String;), in class :Lcom/zxx/andfixdemo/BuildConfig;
        at com.euler.patch.diff.DiffInfo.addModifiedFields(DiffInfo.java:88)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:125)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:101)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:95)
        at com.euler.patch.diff.DexDiffer.diff(DexDiffer.java:32)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:68)
        at com.euler.patch.Main.main(Main.java:97)

**Comment by NickRobin** [comment]
AndFix限制修改 BuildConfig 中的内容;

**Comment by wvisible** [comment]
我遇到这个问题是打了一个release版和一个debug版，就遇到这个问题了，都打成release就没这个问题
