### ISSUE TITLE
5.0以上系统加载apatch出现ANR

### ISSUE THREAD

**Issue by CHNfred** [alibaba/AndFix#138]
5.0以上系统加载apatch出现ANR，三星note3的5.0系统、OnePlus-OneA2001手机的5.1.1系统加载apatch补丁均出现anr，我尝试把加载addPatch()的调用放到异步去处理，还是ANR。小米4的4.4系统则正常，还请帮忙分析一下原因

**Comment by CHNfred** [comment]
02-26 14:59:15.230 7679-7679/? E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
02-26 14:59:16.866 7679-7679/? W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
02-26 14:59:16.866 7679-7679/? E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
02-26 14:59:17.848 6903-7006/? D/HeadsetStateMachine: Disconnected process message: 10, size: 0
02-26 14:59:18.485 7679-7679/? W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
02-26 14:59:18.485 7679-7679/? E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
02-26 14:59:20.128 7679-7679/? W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
02-26 14:59:20.128 7679-7679/? E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
02-26 14:59:21.151 1143-1237/? W/MountService: getVolumeState(/storage/emulated/0/external_sd): Unknown volume
02-26 14:59:21.157 1143-17317/? W/MountService: getVolumeState(/mnt/sdcard-ext): Unknown volume
02-26 14:59:21.160 1143-4462/? W/MountService: getVolumeState(/mnt/ext_sdcard): Unknown volume
02-26 14:59:21.165 1143-1163/? W/MountService: getVolumeState(/mnt/sdcard2): Unknown volume
02-26 14:59:21.168 1143-4484/? W/MountService: getVolumeState(/mnt/emmc): Unknown volume
02-26 14:59:21.175 1143-4413/? W/MountService: getVolumeState(/mnt/extSdCard): Unknown volume
02-26 14:59:21.179 1143-4218/? W/MountService: getVolumeState(/mnt/sdcard/SD_CARD): Unknown volume
02-26 14:59:21.184 1143-1162/? W/MountService: getVolumeState(/mnt/sdcard/extra_sd): Unknown volume
02-26 14:59:21.188 1143-4427/? W/MountService: getVolumeState(/mnt/extrasd_bind): Unknown volume
02-26 14:59:21.190 1143-4424/? W/MountService: getVolumeState(/mnt/sdcard/ext_sd): Unknown volume
02-26 14:59:21.195 1143-4461/? W/MountService: getVolumeState(/storage/extSdCard): Unknown volume
02-26 14:59:21.198 1143-1237/? W/MountService: getVolumeState(/storage/sdcard1): Unknown volume
02-26 14:59:21.201 1143-17317/? W/MountService: getVolumeState(/mnt/sdcard/external_SD): Unknown volume
02-26 14:59:21.207 1143-4462/? W/MountService: getVolumeState(/mnt/sdcard/external_sd): Unknown volume
02-26 14:59:21.282 4643-5054/? V/ContactsProvider2: query: uri=content://com.android.contacts/raw_contacts  projection=[_id]  selection=[deleted=0]  args=null  order=[null] CPID=4055 User=0
02-26 14:59:21.468 4643-5054/? D/CallLogProvider: add selection is_blacklist==0
02-26 14:59:21.563 1143-4427/? W/MountService: getVolumeState(/storage/emulated/0/external_sd): Unknown volume
02-26 14:59:21.565 1143-4424/? W/MountService: getVolumeState(/mnt/sdcard-ext): Unknown volume
02-26 14:59:21.567 1143-4461/? W/MountService: getVolumeState(/mnt/ext_sdcard): Unknown volume
02-26 14:59:21.568 1143-1237/? W/MountService: getVolumeState(/mnt/sdcard2): Unknown volume
02-26 14:59:21.569 1143-17317/? W/MountService: getVolumeState(/mnt/emmc): Unknown volume
02-26 14:59:21.571 1143-4462/? W/MountService: getVolumeState(/mnt/extSdCard): Unknown volume
02-26 14:59:21.572 1143-4413/? W/MountService: getVolumeState(/mnt/sdcard/SD_CARD): Unknown volume
02-26 14:59:21.574 1143-1163/? W/MountService: getVolumeState(/mnt/sdcard/extra_sd): Unknown volume
02-26 14:59:21.576 1143-4218/? W/MountService: getVolumeState(/mnt/extrasd_bind): Unknown volume
02-26 14:59:21.577 1143-4484/? W/MountService: getVolumeState(/mnt/sdcard/ext_sd): Unknown volume
02-26 14:59:21.580 1143-1162/? W/MountService: getVolumeState(/storage/extSdCard): Unknown volume
02-26 14:59:21.581 1143-4427/? W/MountService: getVolumeState(/storage/sdcard1): Unknown volume
02-26 14:59:21.583 1143-4424/? W/MountService: getVolumeState(/mnt/sdcard/external_SD): Unknown volume
02-26 14:59:21.585 1143-4461/? W/MountService: getVolumeState(/mnt/sdcard/external_sd): Unknown volume
02-26 14:59:21.716 7679-7679/? W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
02-26 14:59:21.717 7679-7679/? E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
02-26 14:59:22.835 701-701/? I/MSM-irqbalance: Decided to move IRQ240 from CPU3 to CPU2
02-26 14:59:23.336 7679-7679/? W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
02-26 14:59:23.337 7679-7679/? E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
02-26 14:59:23.853 6903-7006/? D/HeadsetStateMachine: Disconnected process message: 10, size: 0
02-26 14:59:24.996 7679-7679/? W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
02-26 14:59:24.997 7679-7679/? E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
02-26 14:59:26.633 7679-7679/? W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
02-26 14:59:26.633 7679-7679/? E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
02-26 14:59:27.834 701-701/? I/MSM-irqbalance: Decided to move IRQ222 from CPU2 to CPU0
02-26 14:59:28.162 4055-4055/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.lbe.security.service.core.client.p.a(android.content.ComponentName, int, android.app.Notification)' on a null object reference
02-26 14:59:28.163 4055-4055/? W/System.err:     at com.lbe.security.service.core.client.proxy.a.c(ActivityService.java:284)
02-26 14:59:28.163 4055-4055/? W/System.err:     at com.lbe.security.service.core.client.proxy.d.onTransact(ActivityService.java:65)
02-26 14:59:28.163 4055-4055/? W/System.err:     at android.os.Binder.transact(Binder.java:380)
02-26 14:59:28.163 4055-4055/? W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
02-26 14:59:28.163 4055-4055/? W/System.err:     at android.os.BinderProxy.transact(Binder.java:496)
02-26 14:59:28.163 4055-4055/? W/System.err:     at android.app.ActivityManagerProxy.setServiceForeground(ActivityManagerNative.java:3519)
02-26 14:59:28.163 4055-4055/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-26 14:59:28.163 4055-4055/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
02-26 14:59:28.163 4055-4055/? W/System.err:     at com.morgoo.droidplugin.c.d.a(Unknown Source)
02-26 14:59:28.163 4055-4055/? W/System.err:     at com.morgoo.droidplugin.c.c.i.invoke(Unknown Source)
02-26 14:59:28.163 4055-4055/? W/System.err:     at com.morgoo.droidplugin.c.c.a.invoke(Unknown Source)
02-26 14:59:28.163 4055-4055/? W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:397)
02-26 14:59:28.163 4055-4055/? W/System.err:     at $Proxy14.setServiceForeground(Unknown Source)
02-26 14:59:28.163 4055-4055/? W/System.err:     at android.app.Service.startForeground(Service.java:651)
02-26 14:59:28.163 4055-4055/? W/System.err:     at com.qihoo.express.mini.service.DaemonCoreService.a(Unknown Source)
02-26 14:59:28.163 4055-4055/? W/System.err:     at com.qihoo.express.mini.service.DaemonCoreService.onStartCommand(Unknown Source)
02-26 14:59:28.163 4055-4055/? W/System.err:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2896)
02-26 14:59:28.163 4055-4055/? W/System.err:     at android.app.ActivityThread.access$2100(ActivityThread.java:153)
02-26 14:59:28.163 4055-4055/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
02-26 14:59:28.163 4055-4055/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-26 14:59:28.163 4055-4055/? W/System.err:     at android.os.Looper.loop(Looper.java:135)
02-26 14:59:28.163 4055-4055/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5259)
02-26 14:59:28.163 4055-4055/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-26 14:59:28.163 4055-4055/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
02-26 14:59:28.163 4055-4055/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:927)
02-26 14:59:28.163 4055-4055/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:722)
02-26 14:59:28.175 3790-3790/? D/StatusBar: Add Message to List, key=0|com.qihoo.appstore|489348|null|10092, id=489348
02-26 14:59:28.179 3790-4222/? D/StatusBar: handleMessage:0|com.qihoo.appstore|489348|null|10092
02-26 14:59:28.185 3790-3790/? D/StatusBarNotification: is uid system false
02-26 14:59:28.204 3790-3790/? D/PhoneStatusBar: priority from notificationManager is com.qihoo.appstore 0
02-26 14:59:28.205 3790-3790/? D/PhoneStatusBar: priority from notificationManager is com.qihoo.appstore 0
02-26 14:59:28.206 3790-3790/? D/PhoneStatusBar: priority from notificationManager is com.qihoo.appstore 0
02-26 14:59:28.208 3790-3790/? D/PhoneStatusBar: priority from notificationManager is com.qihoo.appstore 0
02-26 14:59:28.208 3790-3790/? D/PhoneStatusBar: priority from notificationManager is com.kingroot.kinguser 0
02-26 14:59:28.209 3790-3790/? D/PhoneStatusBar: priority from notificationManager is android 0
02-26 14:59:28.209 3790-3790/? D/PhoneStatusBar: priority from notificationManager is android 0
02-26 14:59:28.209 3790-3790/? D/StatusBarNotification: is uid system false
02-26 14:59:28.210 3790-3790/? V/PhoneStatusBar: DEBUG_MEDIA: Continuing media notification: key=null
02-26 14:59:28.210 3790-3790/? V/PhoneStatusBar: DEBUG_MEDIA: updating album art for notification null metadata=null metaDataChanged=false state=0
02-26 14:59:28.211 3790-3790/? D/StatusBar: Add Message to List, key=0|com.qihoo.appstore|489348|null|10092, id=489348
02-26 14:59:28.211 3790-3790/? D/StatusBar: Add Message to List, key=0|com.qihoo.appstore|489348|null|10092, id=489348
02-26 14:59:28.250 7679-7679/? W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
02-26 14:59:28.250 7679-7679/? E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
02-26 14:59:28.286 3790-4222/? D/StatusBar: handleMessage:0|com.qihoo.appstore|489348|null|10092
02-26 14:59:28.288 3790-3790/? D/StatusBarNotification: is uid system false
02-26 14:59:28.293 3790-3790/? D/PhoneStatusBar: priority from notificationManager is com.qihoo.appstore 0
02-26 14:59:28.293 3790-3790/? D/PhoneStatusBar: priority from notificationManager is com.qihoo.appstore 0
02-26 14:59:28.293 3790-3790/? D/PhoneStatusBar: priority from notificationManager is com.qihoo.appstore 0
02-26 14:59:28.294 3790-3790/? D/PhoneStatusBar: priority from notificationManager is com.qihoo.appstore 0
02-26 14:59:28.294 3790-3790/? D/PhoneStatusBar: priority from notificationManager is com.kingroot.kinguser 0
02-26 14:59:28.294 3790-3790/? D/PhoneStatusBar: priority from notificationManager is android 0
02-26 14:59:28.294 3790-3790/? D/PhoneStatusBar: priority from notificationManager is android 0
02-26 14:59:28.294 3790-3790/? D/StatusBarNotification: is uid system false
02-26 14:59:28.294 3790-3790/? V/PhoneStatusBar: DEBUG_MEDIA: Continuing media notification: key=null
02-26 14:59:28.295 3790-3790/? V/PhoneStatusBar: DEBUG_MEDIA: updating album art for notification null metadata=null metaDataChanged=false state=0
02-26 14:59:29.847 7679-7679/? W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
02-26 14:59:29.847 7679-7679/? E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
02-26 14:59:29.849 6903-7006/? D/HeadsetStateMachine: Disconnected process message: 10, size: 0
02-26 14:59:31.486 7679-7679/? W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
02-26 14:59:31.487 7679-7679/? E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
02-26 14:59:32.836 701-701/? I/MSM-irqbalance: Decided to move IRQ115 from CPU2 to CPU0
02-26 14:59:33.131 7679-7679/? W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
02-26 14:59:33.131 7679-7679/? E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
02-26 14:59:34.774 7679-7679/? W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
02-26 14:59:34.774 7679-7679/? E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
02-26 14:59:35.853 6903-7006/? D/HeadsetStateMachine: Disconnected process message: 10, size: 0
02-26 14:59:36.407 7679-7679/? W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
02-26 14:59:36.408 7679-7679/? E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
02-26 14:59:37.836 701-701/? I/MSM-irqbalance: Decided to move IRQ215 from CPU2 to CPU0
02-26 14:59:38.043 7679-7679/? W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
02-26 14:59:38.044 7679-7679/? E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
02-26 14:59:39.680 7679-7679/? W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory

**Comment by cokepanm** [comment]
5.0以上及ART模式暂时不推荐使用，我这也遇到很多问题

**Comment by CHNfred** [comment]
嗯 那我先暂时不上线了，等稳定后再集成使用吧。

**Comment by muximus3** [comment]
编译了arm64 么

**Comment by CHNfred** [comment]
编译了arm64-v8a的so，但是项目中有的so是32位的并且没有c的源码，这样运行就报错了，可有好的解决方案，日志如下：
03-03 13:56:22.996 18577-18577/? D/AndroidRuntime: Shutting down VM
03-03 13:56:22.997 18577-18577/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.iflytek.xmmusic.activitys, PID: 18577
                                                   java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.iflytek.xmmusic.activitys-1/lib/arm64/libsecret.so" is 32-bit instead of 64-bit
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                       at java.lang.System.loadLibrary(System.java:988)
                                                       at com.iflytek.jni.SecretJNI.<clinit>(SourceFile:76)
                                                       at com.iflytek.xmmusic.activitys.SplashActivity.onCreate(SourceFile:161)
                                                       at com.iflytek.xmmusic.activitys.BaseActivity.onCreate(SourceFile:42)
                                                       at android.app.Activity.performCreate(Activity.java:6066)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2280)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:153)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5259)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:927)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:722)
03-03 13:56:22.998 1143-4368/? W/ActivityManager:   Force finishing activity 1 com.iflytek.xmmusic.activitys/.SplashActivity
