### ISSUE TITLE
apkpatch 抛异常，无法生成布丁文件

### ISSUE THREAD

**Issue by busymilk** [alibaba/AndFix#139]
自己建了一个简单的helloword工程，结果用apkpatch.sh来使用，抛出如下异常：
java.lang.RuntimeException: can,t modified Field:VERSION_CODE(I), in class :Lmyself/myapplication/BuildConfig;
	at com.euler.patch.diff.DiffInfo.addModifiedFields(DiffInfo.java:88)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:125)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:101)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:95)
	at com.euler.patch.diff.DexDiffer.diff(DexDiffer.java:32)
	at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:68)
	at com.euler.patch.Main.main(Main.java:97)

**Comment by pzhangleo** [comment]
不支持增加成员变量

**Comment by busymilk** [comment]
新旧版本之间没有做任何增加成员变量操作，只在MainActivity中一个boolean属性由false改为true，结果就失败了。。。

**Comment by pzhangleo** [comment]
那估计就是对成员变量的修改都不支持，但是他们内部的andfix应该已经实现了这部分功能了

**Comment by w4lle** [comment]
public void addAddedFields(DexBackedField field) {
  addedFields.add(field);
  throw new RuntimeException("can,t add new Field:" + 
    field.getName() + "(" + field.getType() + "), " + "in class :" + 
    field.getDefiningClass());
}

public void addModifiedFields(DexBackedField field) {
  modifiedFields.add(field);
  throw new RuntimeException("can,t modified Field:" + 
    field.getName() + "(" + field.getType() + "), " + "in class :" + 
    field.getDefiningClass());
}

官方的apkPatch工具不支持成员变量的增加和修改

**Comment by busymilk** [comment]
看来只能改方法了。。。

**Comment by huangchenggang** [comment]
D:\code\android\architecture\AndFix-master\apkpatch-1.0.3>apkpatch -f LiumiAppTe
st_v2.0.0.20160503_debug.apk -t LiumiAppTest_v2.0.0.20160429_debug.apk -o output
1 -k debug.keystore -p android -a androiddebugkey -e android
java.lang.RuntimeException: can,t modified Field:VERSION_NAME(Ljava/lang/String;
), in class :Lcn/memedai/liumi/BuildConfig;
        at com.euler.patch.diff.DiffInfo.addModifiedFields(DiffInfo.java:88)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:125)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:101)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:95)
        at com.euler.patch.diff.DexDiffer.diff(DexDiffer.java:32)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:68)
        at com.euler.patch.Main.main(Main.java:97)
这是什么鬼？
