### ISSUE TITLE
merge .apatch files Exception in thread "main" java.lang.IllegalArgumentException:

### ISSUE THREAD

**Issue by iverking** [alibaba/AndFix#14]
Exception in thread "main" java.lang.IllegalArgumentException:  does not exist
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1637)
        at com.euler.patch.Build.<init>(Build.java:50)
        at com.euler.patch.MergePatch.<init>(MergePatch.java:24)
        at com.euler.patch.Main.main(Main.java:76)

**Comment by supern** [comment]
merge？
usage: apkpatch -m <apatch_path...> -k <keystore> -p <***> -a <alias> -e <***> -o out

**Comment by iverking** [comment]
java.io.FileNotFoundException: G:\out\merge.dex (系统找不到指定的文件。)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.euler.patch.build.SignedJarBuilder.writeFile(SignedJarBuilder.jav
a:152)
        at com.euler.patch.build.PatchBuilder.<init>(PatchBuilder.java:25)
        at com.euler.patch.Build.build(Build.java:81)
        at com.euler.patch.MergePatch.doMerge(MergePatch.java:35)
        at com.euler.patch.Main.main(Main.java:78)
java.io.FileNotFoundException: G:\out\merge.dex (系统找不到指定的文件。)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.euler.patch.Build.release(Build.java:59)
        at com.euler.patch.MergePatch.doMerge(MergePatch.java:37)
        at com.euler.patch.Main.main(Main.java:78)

**Comment by iverking** [comment]
@supern G:\tools>apkpatch -m G:\output\2-4da8c6d873ab69afee99fa31c3291623.apatch -o G:\o
ut -k G:\keystore\sztkeystore -p 123456 -a lucky -e 123456
java.io.FileNotFoundException: G:\out\merge.dex (系统找不到指定的文件。)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.euler.patch.build.SignedJarBuilder.writeFile(SignedJarBuilder.jav
a:152)
        at com.euler.patch.build.PatchBuilder.<init>(PatchBuilder.java:25)
        at com.euler.patch.Build.build(Build.java:81)
        at com.euler.patch.MergePatch.doMerge(MergePatch.java:35)
        at com.euler.patch.Main.main(Main.java:78)
java.io.FileNotFoundException: G:\out\merge.dex (系统找不到指定的文件。)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.euler.patch.Build.release(Build.java:59)
        at com.euler.patch.MergePatch.doMerge(MergePatch.java:37)
        at com.euler.patch.Main.main(Main.java:78)

**Comment by supern** [comment]
@iverking merge是指多个apatch文件合并，对于插件化架构的app，每个插件可能生成一个apatch，这个时候有多个apatch合并的需求了。你其实只需要生成就好了

**Comment by iverking** [comment]
@supern 是这样啊，那谢谢了
