### ISSUE TITLE
这是什么意思？我只是修改了一个Toast

### ISSUE THREAD

**Issue by ting0220** [alibaba/AndFix#141]
java.lang.RuntimeException: can,t modified Field:d(Ljava/lang/String;), in class :Lcom/businessvalue/android/app/a;
	at com.euler.patch.diff.DiffInfo.addModifiedFields(DiffInfo.java:88)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:125)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:101)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:95)
	at com.euler.patch.diff.DexDiffer.diff(DexDiffer.java:32)
	at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:68)
	at com.euler.patch.Main.main(Main.java:97)

**Comment by busymilk** [comment]
好像只能改方法。。。。

**Comment by liericiyan** [comment]
不能直接修改变量的值

**Comment by busymilk** [comment]
对，试了试，变量改不了，不过方法的添加修改，删除，都可以

**Comment by ting0220** [comment]
Toast里边的弹出消息应该不算是变量吧

**Comment by busymilk** [comment]
你是咋写的

**Comment by ting0220** [comment]
把toast里边的123改成456了，，，

**Comment by busymilk** [comment]
。。。。。这么奇葩。。去了混淆试试？

**Comment by ting0220** [comment]
并没有混淆，有时间我再看看吧，嘿嘿
