### ISSUE TITLE
 java.lang.IllegalAccessError: Method 'void  Android 5.0 兼容？

### ISSUE THREAD

**Issue by javaliquan** [alibaba/AndFix#146]
java.lang.IllegalAccessError: Method 'void com.dwl.uh.ui.activity.usercenter.OrderDetailActivity_CF.getOrderTrackInfo()' is inaccessible to class 'com.dwl.uh.ui.activity.usercenter.OrderDetailActivity_CF' (declaration of 'com.dwl.uh.ui.activity.usercenter.OrderDetailActivity_CF' appears in /data/data/com.dwl.uh/files/apatch/1.5_45_20160303_cancleorderTest_07.apatch)
	at com.dwl.uh.ui.activity.usercenter.OrderDetailActivity_CF.getOrderDetailSuccess(OrderDetailActivity.java:526)
	at com.dwl.uh.manager.presenter.OrderDetailPresenter$1.onSuccess(OrderDetailPresenter.java:46)
	at com.dwl.uh.manager.model.impl.OrderDetailModelImpl$1.onResponse(OrderDetailModelImpl.java:22)
	at com.dwl.uh.manager.model.impl.OrderDetailModelImpl$1.onResponse(OrderDetailModelImpl.java:1)
	at com.dwl.uh.net.GsonRequest.deliverResponse(GsonRequest.java:93)
	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5275)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)

**Comment by sx1923** [comment]
java.lang.IllegalAccessError问题解决了吗？4.4.4版本不崩溃 ， 未替换成功 5.1.1版本崩溃

**Comment by javaliquan** [comment]
没有

**Comment by cy20061121** [comment]
同样的问题啊。

**Comment by jianghao1123** [comment]
6.0替换成功，退出后再进来走一遍流程就会报 method inaccessible ，杀掉进程再进来是好的

**Comment by supermanmwg** [comment]
现在有人解决了吗

**Comment by miluotao** [comment]
看看这篇文章  http://www.jianshu.com/p/58fc4c2cb65a
