### ISSUE TITLE
三星Note，系统5.0，JNI调修改的java方法，报错

### ISSUE THREAD

**Issue by hellokugo** [alibaba/AndFix#147]
步骤：项目的JNI调用方法testApp，修改方法体testApp，生成patch文件进行热修复，报错：

03-17 09:58:49.268: A/art(8927): art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: can't call static void com.example.gege_CF.testApp on class java.lang.Class<com.boyaa.made.LuaEvent>
03-17 09:58:49.268: A/art(8927): art/runtime/check_jni.cc:65]     in call to CallStaticVoidMethodV
03-17 09:58:49.268: A/art(8927): art/runtime/check_jni.cc:65]     from void com.xxxx.made.AppRenderer.nativeTouchesEnd(int, float, float, long)
03-17 09:58:49.268: A/art(8927): art/runtime/check_jni.cc:65] "GLThread.Lua" prio=5 tid=19 Runnable

在5.0手机之前测试没有问题，5.0就有问题了，怀疑是ART平台JNI调用修改JAVA方法有问题，大家有遇到过吗？

**Comment by a14795860** [comment]
红米note2也是崩溃了，我拿其他机子跑就没问题
java.lang.UnsatisfiedLinkError: No implementation found for boolean com.alipay.euler.andfix.AndFix.setup(boolean, int) (tried Java_com_alipay_euler_andfix_AndFix_setup and Java_com_alipay_euler_andfix_AndFix_setup__ZI)
                                                       at com.alipay.euler.andfix.AndFix.setup(Native Method)
                                                       at com.alipay.euler.andfix.AndFix.setup(AndFix.java:113)

**Comment by bsp0911932** [comment]
你们这个问题就是因为缺arm64的so库啊，自己build一个就行了，妥妥的

**Comment by hellokugo** [comment]
不是so库的问题，是修改了java方法里的static方法，该方法同时也是native层 c回调的方法，你可以测试下。
这种情况下AndFix目前应该是不支持的，涉及到hook native层，应该是所有机型都会报错。但是由于5.0以下native层对异常没有做严格处理，所以5.0以下机型会提示warning但不会崩溃。

![error](https://cloud.githubusercontent.com/assets/10484766/15236546/52ad1cfe-18f8-11e6-9c97-c61d42e53ebf.jpg)

由于本人对native层不熟悉，所以是做了机型判断处理。5.0以上机型采用classLoader热修复方式，同时也不用处理CLASS_ISPREVERIFIED问题（在5.0以上机型google已去掉该标志位），5.0以下继续沿用AndFix热修复。
