### ISSUE TITLE
apkpatch有bug，只要方法中有形如int[] nums = new int[] {1, 2, 3}的定义，都会判断为有更改

### ISSUE THREAD

**Issue by kkmoving** [alibaba/AndFix#16]
方法中有形如int[] nums = new int[] {1, 2, 3}的定义，apkpatch都会判断为有更改。

另外，apkpatch的代码有否开源出来？

**Comment by supern** [comment]
@kkmoving  后续会开源，目前有些不稳定

**Comment by supern** [comment]
@kkmoving apkpatch更新了

**Comment by gdgm123** [comment]
为啥系统组件的方法不起作用，一定是自己自定义的方法才能替换成功吗

**Comment by gdgm123** [comment]
java.util.zip.ZipException: File too short to be a zip file: 0
            at java.util.zip.ZipFile.readCentralDir(ZipFile.java:355)
            at java.util.zip.ZipFile.<init>(ZipFile.java:151)
            at java.util.zip.ZipFile.<init>(ZipFile.java:115)
            at java.util.jar.JarFile.<init>(JarFile.java:166)
            at java.util.jar.JarFile.<init>(JarFile.java:152)
            at com.alipay.euler.andfix.patch.Patch.init(Patch.java:75)
            at com.alipay.euler.andfix.patch.Patch.<init>(Patch.java:67)
            at com.alipay.euler.andfix.patch.PatchManager.addPatch(PatchManager.java:125)
            at com.alipay.euler.andfix.patch.PatchManager.initPatchs(PatchManager.java:111)
            at com.alipay.euler.andfix.patch.PatchManager.init(PatchManager.java:104)
            at com.example.administrator.myapplication.MyApp.onCreate(MyApp.java:25)

**Comment by supern** [comment]
@gdgm123 系统组件支持的啊。你这个是补丁size为0了，检查下补丁的生成以及上传

**Comment by gdgm123** [comment]
改了文件名为out, 修改了方法里一个变量为啥补丁生成size为0
![image](https://cloud.githubusercontent.com/assets/8435690/10016282/5e49b598-6158-11e5-961e-f314716ae23d.png)

**Comment by supern** [comment]
@gdgm123 是放到sdcrad的根目录么

**Comment by gdgm123** [comment]
是sdcard根目录，检查过了

**Comment by supern** [comment]
感觉读的路径不对

**Comment by gdgm123** [comment]
@supern 
换了一台1加手机就报下面这个错误
09-23 09:57:22.031    6725-6725/com.example.administrator.myapplication E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.administrator.myapplication, PID: 6725
    java.lang.IllegalAccessError: interface not accessible
            at dalvik.system.DexFile.defineClassNative(Native Method)
            at dalvik.system.DexFile.defineClass(DexFile.java:222)
            at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:215)
            at dalvik.system.DexFile.loadClass(DexFile.java:204)
            at com.alipay.euler.andfix.AndFixManager.fix(AndFixManager.java:177)
            at com.alipay.euler.andfix.patch.PatchManager.loadPatch(PatchManager.java:210)
            at com.example.administrator.myapplication.MyApp.onCreate(MyApp.java:30)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4473)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by supern** [comment]
@gdgm123 apkpatch是1.0.3吗

**Comment by gdgm123** [comment]
@supern  不是1.0.3 ，不过我是以release方式测试的，稍等，我用1.0.3版测下

**Comment by gdgm123** [comment]
@supern  刚试了1.0.3不会出现这两个异常了，弱弱问下是什么原因导致的？

**Comment by supern** [comment]
@gdgm123 打包工具有bug，生成了多余的代码

**Comment by gdgm123** [comment]
@supern 哦哦，手机碎片化系统兼容性如何？最新版可以应用部署到线上商业项目吗

**Comment by supern** [comment]
@gdgm123 我们做过大规模的测试，可以部署的，我们其实就在用

**Comment by aso210** [comment]
apkpatch.jar 能开源出来吗？
