### ISSUE TITLE
Caught a RuntimeException from the binder stub implementation.

### ISSUE THREAD

**Issue by sx1923** [alibaba/AndFix#162]
03-19 08:27:04.818  1320 31177 W Binder  : Caught a RuntimeException from the binder stub implementation.
03-19 08:27:04.818  1320 31177 W Binder  : java.lang.NullPointerException
03-19 08:27:04.818  1320 31177 W Binder  : 	at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
03-19 08:27:04.818  1320 31177 W Binder  : 	at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
03-19 08:27:04.818  1320 31177 W Binder  : 	at android.os.Binder.execTransact(Binder.java:404)
03-19 08:27:04.818  1320 31177 W Binder  : 	at dalvik.system.NativeStart.run(Native Method)

**Comment by sx1923** [comment]
第一次运行正常，第二次运行报错如上。。不是必先，目前发现在小米 4.4系统上出现
