### ISSUE TITLE
一直报IllegalAccessError的错误，怎么解决呢

### ISSUE THREAD

**Issue by macjay** [alibaba/AndFix#165]
我的错误信息如下  

java.lang.IllegalAccessError: Method 'void com.hecaifu.renhe.ui.user.PersonalDataActivity_CF.initView()' is inaccessible to class 'com.hecaifu.renhe.ui.user.PersonalDataActivity' (declaration of 'com.hecaifu.renhe.ui.user.PersonalDataActivity' appears in /data/data/com.hecaifu.renhe/files/instant-run/dex/slice-slice_9-classes.dex)
                                                                       at com.hecaifu.renhe.ui.user.PersonalDataActivity.onCreate(PersonalDataActivity.java:111)
                                                                       at android.app.Activity.performCreate(Activity.java:5990)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by jerryjobs** [comment]
同样的，我也遇到了这个问题。

**Comment by vaqh** [comment]
解决了吗，我也有这个问题

**Comment by iknow4** [comment]
@vaqh
请问你用的Andfix是什么版本？

**Comment by vaqh** [comment]
@iknow4 
0.4.0

**Comment by iknow4** [comment]
我发现最新版本0.5.0也会有类似的报错，但是切到0.4.0就是ok的。

**Comment by vaqh** [comment]
@iknow4 我忘记我当时是在什么情况下报错了，现在貌似没有遇到了
