### ISSUE TITLE
红米note2会崩溃

### ISSUE THREAD

**Issue by a14795860** [alibaba/AndFix#168]
java.lang.UnsatisfiedLinkError:
 No implementation found for boolean com.alipay.euler.andfix.AndFix.setup(boolean, int) 
(tried Java_com_alipay_euler_andfix_AndFix_setup and Java_com_alipay_euler_andfix_AndFix_setup__ZI)
                                                                            
at com.alipay.euler.andfix.AndFix.setup(Native Method)
                                                                           
 at com.alipay.euler.andfix.AndFix.setup(AndFix.java:113)
                                                                           
 at com.alipay.euler.andfix.Compat.isSupport(Compat.java:45)
                                                                           
 at com.alipay.euler.andfix.AndFixManager.<init>(AndFixManager.java:74)
                                                                            
at com.alipay.euler.andfix.patch.PatchManager.<init>(PatchManager.java:78)

**Comment by a14795860** [comment]
之前0.3.1版本时，认为是缺失对应的SO库。现在更新到0.4.0，已经有新增了arm64的SO库，但是还是会崩溃，我也崩溃了~~~

**Comment by showsoon** [comment]
你这个问题应该是so库没有打进程序中。你引的 aar 默认只编译了 arm与x86 的 so 。arm64 so 需要你添加到 lib 下面的abi 目录。可以通过反编译查看是否添加进去了 so。
