### ISSUE TITLE
RuntimeException: can,t modified Field:action0(I), in class :Landroid/support/v7/appcompat/R$id;

### ISSUE THREAD

**Issue by YijingwanWang** [alibaba/AndFix#172]
Hi all,我遇到了这样的错误不知道是什么原因造成的有谁能给些指导么谢谢了H:\AndFixTest>apkpatch.bat -f XXX.apk -t XXX.apk -o output -k XXX.keystore -p android -a XXX-e XXX
java.lang.RuntimeException: can,t modified Field:action0(I), in class :Landroid/support/v7/appcompat/R$id;
at com.euler.patch.diff.DiffInfo.addModifiedFields(DiffInfo.java:88)
at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:125)
at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:101)
at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:95)
at com.euler.patch.diff.DexDiffer.diff(DexDiffer.java:32)
at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:68)
at com.euler.patch.Main.main(Main.java:97)

**Comment by ljluestc** [comment]
这个错误表明在进行补丁操作时，AndFix无法修改android/support/v7/appcompat/R$id类中的action0字段。这可能是由于该字段被标记为不可修改或访问，导致AndFix无法进行补丁操作。

确保使用的AndFix版本与的项目兼容。有时，AndFix的旧版本可能不支持某些类库或框架，导致无法进行补丁操作。尝试升级到最新版本的AndFix，或查看AndFix的文档和支持资源以了解与正在使用的类库或框架的兼容性。

检查的补丁操作是否正确。确保使用的补丁工具和参数正确，并且目标类和字段名称是正确的。仔细检查错误信息中提到的类和字段，确认它们是想要修改的目标。
