### ISSUE TITLE
java.lang.IllegalArgumentException: /smali does not exist

### ISSUE THREAD

**Issue by AlanCheen** [alibaba/AndFix#177]
在跑Demo的时候，生成patch遇到了个错误

命令：
```
./apkpatch.sh  apkpatch -f ./2.apk -t ./1.apk -k /Users/yifeiyuan/.android/debug.keystore -p android -a androiddebugkey -e android
```

错误日志：  
``` java
java.lang.IllegalArgumentException: /smali does not exist
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1637)
	at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:53)
	at com.euler.patch.Main.main(Main.java:97)
```

不知道如何解决，还望指导

**Comment by AlanCheen** [comment]
-o 参数加上去就行了
