### ISSUE TITLE
能给看看不

### ISSUE THREAD

**Issue by caowt** [alibaba/AndFix#190]
java.lang.UnsatisfiedLinkError: No implementation found for boolean com.alipay.euler.andfix.AndFix.setup(boolean, int) (tried Java_com_alipay_euler_andfix_AndFix_setup and Java_com_alipay_euler_andfix_AndFix_setup__ZI)
	at com.alipay.euler.andfix.AndFix.setup(Native Method)
	at com.alipay.euler.andfix.AndFix.setup(Unknown Source)
	at com.alipay.euler.andfix.Compat.isSupport(Unknown Source)
	at com.alipay.euler.andfix.AndFixManager.<init>(Unknown Source)
	at com.alipay.euler.andfix.patch.PatchManager.<init>(Unknown Source)
	at com.anewlives.zaishengzhan.ZaishenghuoApplication.r(Unknown Source)
	at com.anewlives.zaishengzhan.ZaishenghuoApplication.q(Unknown Source)
	at com.anewlives.zaishengzhan.ZaishenghuoApplication.onCreate(Unknown Source)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4726)
	at android.app.ActivityThread.access$1600(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5438)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

小米手机上直接报这个错误……

**Comment by caowt** [comment]
之前用 一直都是好的 很好用 除了没有打arm64的so 库以外……

**Comment by supern** [comment]
@caowt  用新版试试
