### ISSUE TITLE
5.0以上系统首次安装出现anr，有解决方案吗？

### ISSUE THREAD

**Issue by superLY91** [alibaba/AndFix#194]
DALVIK THREADS (57):
 159 "main" prio=5 tid=1 Waiting
 160   | group="main" sCount=1 dsCount=0 obj=0x73832000 self=0xf3c25800
 161   | sysTid=23839 nice=-6 cgrp=default sched=0/0 handle=0xf7706ea0
 162   | state=S schedstat=( 2251881169 360144966 3962 ) utm=127 stm=97 core=2 HZ=100
 163   | stack=0xff034000-0xff036000 stackSize=8MB
 164   | held mutexes=
 165   at com.demo.activity.MyActivity.onCreate(MyActivity.java:79)
 166   - waiting on <0x3d3c7adf> (a java.lang.Class<com.demo.activity.MyActivity_CF>)
 167   at android.app.Activity.performCreate(Activity.java:5990)
 168   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
 169   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
 170   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
 171   at android.app.ActivityThread.access$800(ActivityThread.java:151)
 172   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
 173   at android.os.Handler.dispatchMessage(Handler.java:102)
 174   at android.os.Looper.loop(Looper.java:135)
 175   at android.app.ActivityThread.main(ActivityThread.java:5254)
 176   at java.lang.reflect.Method.invoke!(Native method)
 177   at java.lang.reflect.Method.invoke(Method.java:372)
 178   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
 179   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by supern** [comment]
试下新版本

**Comment by zhaobenbing** [comment]
我试了，0.5.0版本也不行，首次anr

**Comment by superLY91** [comment]
addPatch放到主线程中
