### ISSUE TITLE
loadLibrary

### ISSUE THREAD

**Issue by menghuanmusic** [alibaba/AndFix#197]
java.lang.UnsatisfiedLinkError: Couldn't load andfix from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.test-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.test-1, /vendor/lib, /system/lib]]]: findLibrary returned null
                                                          at java.lang.Runtime.loadLibrary(Runtime.java:358)
                                                          at java.lang.Runtime.loadLibrary(Runtime.java:348)
                                                          at com.alipay.euler.andfix.AndFix.<clinit>(AndFix.java:37)
                                                          at com.alipay.euler.andfix.Compat.isSupport(Compat.java:45)
                                                          at com.alipay.euler.andfix.AndFixManager.<init>(AndFixManager.java:74)
                                                          at com.alipay.euler.andfix.patch.PatchManager.<init>(PatchManager.java:78)
                                                          at com.test.app.MainApplication.initAndFix(MainApplication.java:35)
                                                          at com.test.app.MainApplication.onCreate(MainApplication.java:26)
                                                          at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4889)
                                                          at android.app.ActivityThread.access$1600(ActivityThread.java:174)
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381)
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:146)
                                                          at android.app.ActivityThread.main(ActivityThread.java:5752)
                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by kevenshao** [comment]
目前andfix只编译armeabi和x86架构的so，其它的还没有，如果用的AndroidStudio，可以把打包后的APK解开看看，可能你打包时也包含了armeabi-v7和64位架构的，而这些里面并没有对应的so，所以出现问题。 可以配置一下，打包时只打包armeabi和x86这两个架构类型。

**Comment by menghuanmusic** [comment]
如何配置成只打包armeabi和x86，是否对原来需要用到的v7和其他的有影响？

**Comment by kevenshao** [comment]
目前我这边使用没有遇到什么问题，因为32位的so也是可以在64位跑的，应该是64位的so跑在64位机器上性能更好吧。 不过使用过程感觉不到，另外你可以参考下其它app，如美团，百度，360等等，解包看看，基本上都只保留armeabi和x86，有很多就只保留armeabi.

**Comment by menghuanmusic** [comment]
好的，谢谢了。我试一试。
