### ISSUE TITLE
PatchManager: addPatch报异常，改怎么解决？？求大神指点

### ISSUE THREAD

**Issue by congtaowang** [alibaba/AndFix#211]
PatchManager: addPatch
                                                         java.util.zip.ZipException: Not a zip archive
                                                             at java.util.zip.ZipFile.readCentralDir(ZipFile.java:385)
                                                             at java.util.zip.ZipFile.<init>(ZipFile.java:163)
                                                             at java.util.jar.JarFile.<init>(JarFile.java:199)
                                                             at java.util.jar.JarFile.<init>(JarFile.java:182)
                                                             at java.util.jar.JarFile.<init>(JarFile.java:168)
                                                             at com.alipay.euler.andfix.patch.Patch.init(Patch.java:75)
                                                             at com.alipay.euler.andfix.patch.Patch.<init>(Patch.java:67)
                                                             at com.alipay.euler.andfix.patch.PatchManager.addPatch(PatchManager.java:126)
                                                             at com.alipay.euler.andfix.patch.PatchManager.addPatch(PatchManager.java:163)
                                                             at ct.andfix.AndFixPatchManager$1.onPostExecute(AndFixPatchManager.java:82)
                                                             at ct.andfix.AndFixPatchManager$1.onPostExecute(AndFixPatchManager.java:38)
                                                             at android.os.AsyncTask.finish(AsyncTask.java:636)
                                                             at android.os.AsyncTask.access$500(AsyncTask.java:177)
                                                             at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                             at android.os.Looper.loop(Looper.java:135)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5506)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:952)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)

**Comment by txf4311** [comment]
】
