### ISSUE TITLE
SignatureException

### ISSUE THREAD

**Issue by linsea** [alibaba/AndFix#217]
在华为荣耀7(android 5.0.2)的机子上，加载.apatch文件时遇到如下错误, 但我前后两个包都有签名的：
```
07-25 20:17:13.881 23687-23687/com.abc.andfixdemo E/SecurityChecker: /data/data/com.abc.andfixdemo/files/apatch/patch3.apatch
  java.security.SignatureException
	  at com.android.org.conscrypt.OpenSSLX509Certificate.verifyOpenSSL(OpenSSLX509Certificate.java:353)
	  at com.android.org.conscrypt.OpenSSLX509Certificate.verify(OpenSSLX509Certificate.java:384)
	  at com.alipay.euler.andfix.security.SecurityChecker.check(SecurityChecker.java:158)
	  at com.alipay.euler.andfix.security.SecurityChecker.verifyApk(SecurityChecker.java:124)
	  at com.alipay.euler.andfix.AndFixManager.fix(AndFixManager.java:127)
	  at com.alipay.euler.andfix.patch.PatchManager.loadPatch(PatchManager.java:238)
	  at com.alipay.euler.andfix.patch.PatchManager.addPatch(PatchManager.java:165)
	  at com.abc.andfixdemo.MainActivity$3$1.onResponse(MainActivity.java:67)
	  at com.abc.andfixdemo.MainActivity$3$1.onResponse(MainActivity.java:51)
	  at com.zhy.http.okhttp.OkHttpUtils$4.run(OkHttpUtils.java:194)
	  at android.os.Handler.handleCallback(Handler.java:739)
	  at android.os.Handler.dispatchMessage(Handler.java:95)
	  at android.os.Looper.loop(Looper.java:135)
	  at android.app.ActivityThread.main(ActivityThread.java:5539)
	  at java.lang.reflect.Method.invoke(Native Method)
	  at java.lang.reflect.Method.invoke(Method.java:372)
	  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by zhangxiaang** [comment]
我也遇到这个问题，但是我rebuild一下 就解决了

**Comment by sunyy628** [comment]
如果为错误的补丁包，会报这个错误，我这边因为下载了一个有问题的补丁包

**Comment by supern** [comment]
签名不对
