### ISSUE TITLE
apkpatch生成patch文件报错

### ISSUE THREAD

**Issue by lferic** [alibaba/AndFix#218]
apkpatch -f newapp.apk -t oldapp.apk -o outputdic -k dex1.jks -p 123456 -a mykey -e 123456
java.lang.RuntimeException: can,t modified Field:action0(I), in class :Landroid/support／v7/appcompat/R$id;
        at com.euler.patch.diff.DiffInfo.addModifiedFields(DiffInfo.java:88)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:125)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:101)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:95)
        at com.euler.patch.diff.DexDiffer.diff(DexDiffer.java:32)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:68)
        at com.euler.patch.Main.main(Main.java:97)

**Comment by croccio** [comment]
how do you solve?
