### ISSUE TITLE
apkpatch生成patchjava.lang.NullPointerException         at com.euler.patch.build.PatchBuilder.<init>(PatchBuilder.java:5)         at com.euler.patch.Build.build(Build.java:74)         at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:72)         at com.euler.patch.Main.main(Main.java:97) java.lang.NullPointerException         at com.euler.patch.build.PatchBuilder.writeMeta(PatchBuilder.java:33)         at com.euler.patch.Build.build(Build.java:76)         at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:72)         at com.euler.patch.Main.main(Main.java:97) java.lang.NullPointerException         at com.euler.patch.build.PatchBuilder.sealPatch(PatchBuilder.java:43)         at com.euler.patch.Build.build(Build.java:77)         at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:72)         at com.euler.patch.Main.main(Main.java:97)

### ISSUE THREAD

**Issue by lferic** [alibaba/AndFix#219]
C:\Users\LuLearn\Desktop\apkpatch-1.0.3> apkpatch -f newapp.apk -t oldapp.apk -o outputdic -k IPSkeystore -p 123456 -a mykey -e 123456
java.lang.NullPointerException
        at com.euler.patch.build.PatchBuilder.<init>(PatchBuilder.java:5)
        at com.euler.patch.Build.build(Build.java:74)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:72)
        at com.euler.patch.Main.main(Main.java:97)
java.lang.NullPointerException
        at com.euler.patch.build.PatchBuilder.writeMeta(PatchBuilder.java:33)
        at com.euler.patch.Build.build(Build.java:76)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:72)
        at com.euler.patch.Main.main(Main.java:97)
java.lang.NullPointerException
        at com.euler.patch.build.PatchBuilder.sealPatch(PatchBuilder.java:43)
        at com.euler.patch.Build.build(Build.java:77)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:72)
        at com.euler.patch.Main.main(Main.java:97)

**Comment by yqyzxd** [comment]
同样的问题，楼主怎么解决的？
