### ISSUE TITLE
NullPointerException at com.euler.patch.build.PatchBuilder.<init>(PatchBuilder.java:5)

### ISSUE THREAD

**Issue by JuanbingTeam** [alibaba/AndFix#22]
正在尝试使用这个工具，刚更新到了 解决 #20 的版本。

但是 apkpatch.sh输出如下：

add modified Method:V  onCreate(Landroid/os/Bundle;)  in Class:Lcom/***马赛克****/activity/MainTabActivity;
    java.lang.NullPointerException
	at com.euler.patch.build.PatchBuilder.<init>(PatchBuilder.java:5)
	at com.euler.patch.Build.build(Build.java:74)
	at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:72)
	at com.euler.patch.Main.main(Main.java:97)
java.lang.NullPointerException
	at com.euler.patch.build.PatchBuilder.writeMeta(PatchBuilder.java:33)
	at com.euler.patch.Build.build(Build.java:76)
	at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:72)
	at com.euler.patch.Main.main(Main.java:97)
java.lang.NullPointerException
	at com.euler.patch.build.PatchBuilder.sealPatch(PatchBuilder.java:43)
	at com.euler.patch.Build.build(Build.java:77)
	at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:72)
	at com.euler.patch.Main.main(Main.java:97)

希望能有价值～

**Comment by supern** [comment]
签名信息是必须的

**Comment by JuanbingTeam** [comment]
@supern  apk 都是经过 jarsigner 签名的了。  签名后进行了zipalign处理不会有影响吧？下面是我的参数：
./apkpatch.sh -f /Users/LJbin/Documents/patch/new.apk -t /Users/LJbin/Documents/patch/old.apk -o /Users/LJbin/Documents/patch/out/ -k /Users/LJbin/Documents/Workspace/release_key.txt -a patchtest -p key2015 -e key2015

**Comment by supern** [comment]
参数貌似没问题，-a，别名没错吧

**Comment by JuanbingTeam** [comment]
@supern  Thank you!!!! 起初不明白这个alias是干什么的以为是 生成目标文件的文件名。 没反应过来是 签名时候用到的～

再次感谢！！！！

**Comment by chenzjin** [comment]
请教下别名指的是什么？
