### ISSUE TITLE
The apkpatch tool is not open source, and the .so library file is not open source ,is that right?

### ISSUE THREAD

**Issue by yaeio** [alibaba/AndFix#23]
Hi 
 I want to know more detials about  this great project, but i cant find the source file ,why?

**Comment by JuanbingTeam** [comment]
As owner mentioned in other posts, apkpatch tool will be open source later,when it's more stable~

**Comment by yaeio** [comment]
that's good, will the .so library file be open source later,too?

**Comment by supern** [comment]
@yaeio  https://github.com/alibaba/AndFix/tree/master/jni

**Comment by gdgm123** [comment]
@supern 建议将PatchManager初始化以及加载补丁在 Application 中放到子线程去加载，我测试没有问题，这样即使抛异常也不会导致程序崩溃退出，你觉得如何？

**Comment by supern** [comment]
@gdgm123 可以的，但是还是建议开发者自己去平衡，我们有些场景是在启动的时候需要去修复的

**Comment by gdgm123** [comment]
我出现个问题，就是我先安装有bug的apk 然后再载入补丁到sdcard就会报 java.util.zip.ZipException: File too short to be a zip file: 0
            at java.util.zip.ZipFile.readCentralDir(ZipFile.java:355)
            at java.util.zip.ZipFile.<init>(ZipFile.java:151)
            at java.util.zip.ZipFile.<init>(ZipFile.java:115)
            at java.util.jar.JarFile.<init>(JarFile.java:166)
            at java.util.jar.JarFile.<init>(JarFile.java:152)
            at com.alipay.euler.andfix.patch.Patch.init(Patch.java:75)
            at com.alipay.euler.andfix.patch.Patch.<init>(Patch.java:67)
            at com.alipay.euler.andfix.patch.PatchManager.addPatch(PatchManager.java:125)
            at com.alipay.euler.andfix.patch.PatchManager.initPatchs(PatchManager.java:111)
            at com.alipay.euler.andfix.patch.PatchManager.init(PatchManager.java:104)
而我先载入补丁文件到sdcard中再安装存在bug 的apk,就可以替换成功，没问题

**Comment by gdgm123** [comment]
@supern 我出现个问题，就是我先安装有bug的apk 然后再载入补丁到sdcard就会报 java.util.zip.ZipException: File too short to be a zip file: 0
at java.util.zip.ZipFile.readCentralDir(ZipFile.java:355)
at java.util.zip.ZipFile.(ZipFile.java:151)
at java.util.zip.ZipFile.(ZipFile.java:115)
at java.util.jar.JarFile.(JarFile.java:166)
at java.util.jar.JarFile.(JarFile.java:152)
at com.alipay.euler.andfix.patch.Patch.init(Patch.java:75)
at com.alipay.euler.andfix.patch.Patch.(Patch.java:67)
at com.alipay.euler.andfix.patch.PatchManager.addPatch(PatchManager.java:125)
at com.alipay.euler.andfix.patch.PatchManager.initPatchs(PatchManager.java:111)
at com.alipay.euler.andfix.patch.PatchManager.init(PatchManager.java:104)
而我先载入补丁文件到sdcard中再安装存在bug 的apk,就可以替换成功，没问题

**Comment by gdgm123** [comment]
@supern  我犯的错误，现在没事了，没问题，不过建议加载补丁之前做个判断，如果不存在或length等于0就不要加载进去，不然在data/data目录下读到永远是之前length为0的那个补丁

**Comment by honjane** [comment]
不仅仅是补丁包不存在和length为0加判断，补丁包不匹配时也要加判断，不能在data在保存缓存
