### ISSUE TITLE
360加固会出现闪退问题，在5.0以下会有问题，求解决

### ISSUE THREAD

**Issue by tjjlhst** [alibaba/AndFix#230]

**Comment by supern** [comment]
@tjjlhst 日志看看

**Comment by tjjlhst** [comment]
/com.pointercn.yunvs E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.pointercn.yunvs, PID: 16391
                                                                     java.lang.VerifyError: com/pointercn/yunvs/ui/fragment/MoreFragment$$ViewBinder$1
                                                                         at com.pointercn.yunvs.ui.fragment.MoreFragment$$ViewBinder.bind(MoreFragment$$ViewBinder.java:17)
                                                                         at com.pointercn.yunvs.ui.fragment.MoreFragment$$ViewBinder.bind(MoreFragment$$ViewBinder.java:8)
                                                                         at butterknife.ButterKnife.bind(ButterKnife.java:319)
                                                                         at butterknife.ButterKnife.bind(ButterKnife.java:279)
                                                                         at com.pointercn.yunvs.ui.fragment.MoreFragment.onCreateView(MoreFragment.java:203)
                                                                         at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                         at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                         at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
                                                                         at android.os.Handler.handleCallback(Handler.java:733)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                         at dalvik.system.NativeStart.main(Native Method)

**Comment by tjjlhst** [comment]
还是用360加固，在安卓5.0以下会有闪退的问题，试过4.3和4.4都会闪退，试过安卓5.0和6.0没问题
