### ISSUE TITLE
 java.lang.IllegalAccessError: Method

### ISSUE THREAD

**Issue by XuLiucheng** [alibaba/AndFix#232]
Galaxy S7 edge ,Android 6.0.1
手机上首次安装APP，应用补丁，进入activity出错。手机存在APP，用AS运行APP，加载补丁，不出错。
AndroidRuntime: FATAL EXCEPTION: main
   Process: packagename, PID: 26484
   java.lang.IllegalAccessError: Method 'void packagename.xxxActivity_CF.initTitle()'
   is inaccessible to class 'packagename.xxxActivity' 
   (declaration of 'packagename.xxxActivity' 
   appears in /data/data/packagename/files/instant-run/dex/slice-slice_4-classes.dex)
       at packagename.xxxActivity.initViews(xxxActivity.java:599)
       at packagename.xxxActivity.onCreate(xxxActivity.java:527)
       at android.app.Activity.performCreate(Activity.java:6876)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
       at android.app.ActivityThread.access$1100(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7232)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by supern** [comment]
关闭instantrun
