### ISSUE TITLE
apkpatch合并补丁报错

### ISSUE THREAD

**Issue by shidongdi** [alibaba/AndFix#237]
apkpatch -m后报错：
 Out-of-order entry types: 0xc then 0x1
09-06 11:20:49.705 24797-24797/? E/dalvikvm: Trouble with item 2 @ offset 0x444
09-06 11:20:49.705 24797-24797/? E/dalvikvm: Cross-item verify of section type 1003 failed
09-06 11:20:49.705 24797-24797/? E/dalvikvm: ERROR: Byte swap + verify failed
09-06 11:20:49.715 24797-24797/? E/dalvikvm: Optimization failed
09-06 11:20:49.715 24776-24776/? W/dalvikvm: DexOpt: --- END 'out.apatch' --- status=0xff00, process failed
09-06 11:20:49.715 24776-24776/? E/dalvikvm: Unable to extract+optimize DEX from '/data/data/com.robert.today.andfixdemo/files/apatch/out.apatch'
09-06 11:20:49.720 24776-24776/? E/AndFixManager: pacth
                                                  java.io.IOException: unable to open DEX file
                                                      at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                      at dalvik.system.DexFile.openDexFile(DexFile.java:304)
                                                      at dalvik.system.DexFile.<init>(DexFile.java:115)
                                                      at dalvik.system.DexFile.loadDex(DexFile.java:155)
                                                      at com.alipay.euler.andfix.AndFixManager.fix(AndFixManager.java:147)
                                                      at com.alipay.euler.andfix.patch.PatchManager.loadPatch(PatchManager.java:214)
                                                      at com.robert.today.andfixdemo.TestApplication.onCreate(TestApplication.java:25)
                                                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1009)
                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4613)
                                                      at android.app.ActivityThread.access$1800(ActivityThread.java:139)
                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                      at android.os.Looper.loop(Looper.java:136)
                                                      at android.app.ActivityThread.main(ActivityThread.java:5314)
                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                      at dalvik.system.NativeStart.main(Native Method)

-----------------------------
单独的2个补丁是正常的，merge后就报错
补丁生成命令：apkpatch -f andfix_ok_new.apk -t andfix_ok.apk -o output -k test_fix.jks -p sdd123 -a test_fix -e sdd123

合并补丁命令：apkpatch -m out1.apatch out2.apatch -n mergeout -o output -k test_fix.jks -p sdd123 -a test_fix -e sdd123

**Comment by supern** [comment]
我们测试了下，没问题啊

**Comment by shidongdi** [comment]
呃，我再次跑了下，还是发现merge后的patch不生效，虽然有复制到data缓存文件里。目前看来只能跟最早的版本再做一次差分包了

**Comment by supern** [comment]
能把你们的patch包发过来看看
