### ISSUE TITLE
 java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by szhupeng** [alibaba/AndFix#241]
多次打补丁，第一次tvMessage.setText("多次修复了哦");
第二次tvMessage.setText("又改变了内容");
第三次新增一个方法
public String getString(){
   return "新增方法";
}
然后 tvMessage.setText("多次修复了哦");改为tvMessage.setText(getString());结果报错：
java.lang.NoSuchMethodError: No static method access$100(Lcom/dhb/wangcai/activity/MainActivity;)Landroid/widget/TextView; in class Lcom/dhb/xxx/activity/MainActivity_CF; or its super classes (declaration of 'com.dhb.xxx.activity.MainActivity_CF' appears in /data/data/com.dhb.xxx/files/apatch/2084157349.apatch)
                                                       at com.dhb.xxx.activity.MainActivity$2_CF.onClick(MainActivity.java:41)
                                                       at android.view.View.performClick(View.java:4780)
                                                       at android.view.View$PerformClick.run(View.java:19866)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by supern** [comment]
能把补丁文件发上来看看不
