### ISSUE TITLE
sd卡加入 patch后 mPatchManager.init("1.0")后出现这个问题

### ISSUE THREAD

**Issue by YanyeZhang** [alibaba/AndFix#26]
java.util.zip.ZipException: File too short to be a zip file: 0
            at java.util.zip.ZipFile.readCentralDir(ZipFile.java:355)
            at java.util.zip.ZipFile.<init>(ZipFile.java:151)
            at java.util.zip.ZipFile.<init>(ZipFile.java:115)
            at java.util.jar.JarFile.<init>(JarFile.java:166)
            at java.util.jar.JarFile.<init>(JarFile.java:152)
            at com.alipay.euler.andfix.patch.Patch.init(Patch.java:75)
            at com.alipay.euler.andfix.patch.Patch.<init>(Patch.java:67)
            at com.alipay.euler.andfix.patch.PatchManager.addPatch(PatchManager.java:125)
            at com.alipay.euler.andfix.patch.PatchManager.initPatchs(PatchManager.java:111)
            at com.alipay.euler.andfix.patch.PatchManager.init(PatchManager.java:104)

**Comment by supern** [comment]
@YanyeZhang  更新代码or清除数据试试

**Comment by gdgm123** [comment]
@YanyeZhang 在加载补丁之前判断下补丁大小是否大于0,重新试一遍就可以了
