### ISSUE TITLE
点击修复或者打开app  加载加载补丁出现这个问题。修复无效，怎么解决？

### ISSUE THREAD

**Issue by jiangjang** [alibaba/AndFix#263]
E/SecurityChecker: /data/data/amoy.com.test1/files/apatch/first.apatch
   java.security.SignatureException: error:04091077:rsa routines:INT_RSA_VERIFY:wrong signature length
 at com.android.org.conscrypt.NativeCrypto.X509_verify(Native Method)
 at com.alipay.euler.andfix.security.SecurityChecker.check(SecurityChecker.java:158)                                               at com.alipay.euler.andfix.security.SecurityChecker.verifyApk(SecurityChecker.java:124)                                                   at com.alipay.euler.andfix.AndFixManager.fix(AndFixManager.java:127)                                                     at com.alipay.euler.andfix.patch.PatchManager.loadPatch(PatchManager.java:214)
                                                                   at amoy.com.test1.App.onCreate(App.java:32)

**Comment by supern** [comment]
签名问题
