### ISSUE TITLE
生成patch时方法数超限报错如何解决

### ISSUE THREAD

**Issue by TangXun** [alibaba/AndFix#268]
org.jf.util.ExceptionWithContext: Unsigned short value out of range: 87365
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:315)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:997)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:773)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:222)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:200)
	at com.euler.patch.ApkPatch.buildCode(ApkPatch.java:124)
	at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:70)
	at com.euler.patch.Main.main(Main.java:97)

**Comment by TangXun** [comment]
感谢楼主邮件提醒，已经解决了
