### ISSUE TITLE
 java.lang.NoSuchFieldError: pid

### ISSUE THREAD

**Issue by gongwen** [alibaba/AndFix#271]
加载.apatch后，报这个错误，什么问题？
java.lang.NoSuchFieldError: pid
                                                                 at com.gw.andfix.MainActivity.onCreate(MainActivity.java)
                                                                 at android.app.Activity.performCreate(Activity.java:5310)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2381)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2469)
                                                                 at android.app.ActivityThread.access$1100(ActivityThread.java:151)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                 at android.os.Looper.loop(Looper.java:193)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:730)
                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by supern** [comment]
@gongwen com.gw.andfix.MainActivity内容是啥

**Comment by yongli991581716** [comment]
遇到同样问题 求教

**Comment by leonzhuhi** [comment]
@supern   
/*andFix*/
    compile 'com.alipay.euler:andfix:0.5.0@aar'

![Uploading image.png…]()


用新版本出现  （OS 4.4.2）
 Process: com.xiu.app, PID: 470
                                               java.lang.NoSuchFieldError: actionIntent
                                                   at com.xiu.app.moduleothers.other.setting.XiuSettingActivity.initView(XiuSettingActivity.java)
                                                   at com.xiu.app.moduleothers.other.setting.XiuSettingActivity$2.handleMessage(XiuSettingActivity.java:117)
                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                   at android.os.Looper.loop(Looper.java:136)
                                                   at android.app.ActivityThread.main(ActivityThread.java:5315)
                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                   at dalvik.system.NativeStart.main(Native Method)


（OS 6.0.1） java.lang.NoSuchMethodError: No virtual method findViewById(I)Landroid/view/View; in class Lcom/xiu/app/moduleothers/other/setting/XiuSettingActivity_CF; or its super classes (declaration of 'com.xiu.app.moduleothers.other.setting.XiuSettingActivity_CF' appears in /data/user/0/com.xiu.app/files/apatch/306f76a469dad728e53bb51de03c8dca.apatch)
                                                       at com.xiu.app.moduleothers.other.setting.XiuSettingActivity_CF.initView(XiuSettingActivity.java:125)
                                                       at com.xiu.app.moduleothers.other.setting.XiuSettingActivity$2.handleMessage(XiuSettingActivity.java:117)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
