### ISSUE TITLE
无法热修复，一直报错，程序无法运行

### ISSUE THREAD

**Issue by AndroidLevise** [alibaba/AndFix#275]
手机：Nexus5
环境：Android 4.4
报错：
11-03 11:40:53.620 16226-16226/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.yang.tony.andfixdemo, PID: 16226
                                                   java.lang.NoSuchMethodError: Landroid/accessibilityservice/AccessibilityServiceInfo;.getId
                                                       at com.yang.tony.andfixdemo.MainActivity$1.onClick(MainActivity.java)
                                                       at android.view.View.performClick(View.java:4438)
                                                       at android.view.View$PerformClick.run(View.java:18422)
                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by JiangSuyong** [comment]
你用什么andfix 版本是多少？ 我在使用 0.5.0 的时候也是出现 NoSuchMethodError 。然后我使用低版本（0.3.1）后测试成功了。你可以使用低版本看看

**Comment by iHuahua** [comment]
为毛堆栈里有
at com.yang.tony.andfixdemo.MainActivity$1.onClick(MainActivity.java)
我不懂Android，但是看了JNI部分的代码，应该是在程序启动的时候加载patch，也就是onCreate里，程序都启动了再加载管用吗？
