### ISSUE TITLE
生成补丁文件一直报错

### ISSUE THREAD

**Issue by chuwe1** [alibaba/AndFix#276]
C:\Users\chuwe\Desktop\apkpatch>apkpatch -f app2.0.apk -t app1.0.apk -o output -k keystore.jks -p 123456 -a keystore -e 123456

java.lang.RuntimeException: can,t modified Field:VERSION_CODE(I), in class :Lcom/chuwe1/andfixdemo/BuildConfig;
        at com.euler.patch.diff.DiffInfo.addModifiedFields(DiffInfo.java:88)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:125)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:101)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:95)
        at com.euler.patch.diff.DexDiffer.diff(DexDiffer.java:32)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:68)
        at com.euler.patch.Main.main(Main.java:97)

**Comment by yanglichuan** [comment]
metoo
