### ISSUE TITLE
无法生成补丁

### ISSUE THREAD

**Issue by jiangyingjun** [alibaba/AndFix#277]
在demo里没问题 。但生成项目的补丁包时apkpatch报错
D:\jyj\hotfix\apkpatch>apkpatch -f new1.apk -t old1.apk -o D:\jyj\hotfix\apkpatch -k D:\jyj\key\test.keystore -p 666666 -a test.keystore -e 666666
java.lang.NullPointerException
        at com.euler.patch.build.PatchBuilder.<init>(PatchBuilder.java:5)
        at com.euler.patch.Build.build(Build.java:74)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:72)
        at com.euler.patch.Main.main(Main.java:97)
java.lang.NullPointerException
        at com.euler.patch.build.PatchBuilder.writeMeta(PatchBuilder.java:33)
        at com.euler.patch.Build.build(Build.java:76)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:72)
        at com.euler.patch.Main.main(Main.java:97)
java.lang.NullPointerException
        at com.euler.patch.build.PatchBuilder.sealPatch(PatchBuilder.java:43)
        at com.euler.patch.Build.build(Build.java:77)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:72)
        at com.euler.patch.Main.main(Main.java:97)

急用 求大婶解答拉
注：用的com.alipay.euler:andfix:0.5.0@aar  没有混淆  项目生成apk会有两个dex包

**Comment by yqyzxd** [comment]
楼主是怎么解决的？
