### ISSUE TITLE
Compatible problem when working with EventBus

### ISSUE THREAD

**Issue by JuanbingTeam** [alibaba/AndFix#28]
I believe, the class name was changed after patched.  

![test](https://cloud.githubusercontent.com/assets/11962337/10068407/c0fe91fc-62d6-11e5-9ffb-e0bb63e40043.png)

java.lang.IllegalArgumentException: expected receiver of type com.***.activity.MainTabActivity_CF, but got com.***.activity.MainTabActivity
09-24 15:53:29.530 6616-6736/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
09-24 15:53:29.530 6616-6736/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:525)
09-24 15:53:29.530 6616-6736/? E/AndroidRuntime:     at 
de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:498)
09-24 15:53:29.530 6616-6736/? E/AndroidRuntime:     at de.greenrobot.event.EventBus.postToSubscription(EventBus.java:433)
09-24 15:53:29.530 6616-6736/? E/AndroidRuntime:     at de.greenrobot.event.EventBus.postSingleEventForEventType(EventBus.java:410)
09-24 15:53:29.530 6616-6736/? E/AndroidRuntime:     at de.greenrobot.event.EventBus.postSingleEvent(EventBus.java:383)
09-24 15:53:29.530 6616-6736/? E/AndroidRuntime:     at de.greenrobot.event.EventBus.post(EventBus.java:263)

**Comment by JuanbingTeam** [comment]
I am not good at C, C++.

but i guess 'clazz' should be replaced,when replace method.

![image](https://cloud.githubusercontent.com/assets/11962337/10068858/81333966-62da-11e5-96dc-81dd64ec6a19.png)

**Comment by supern** [comment]
EventBus.java:
```
List<SubscriberMethod> subscriberMethods = subscriberMethodFinder.findSubscriberMethods(subscriber.getClass());
```

there have save the class here.

**Comment by supern** [comment]
@JuanbingTeam how about Art?

**Comment by JuanbingTeam** [comment]
@supern  never test on ART....

我的意思是.....Eventbus 存的class name是 onCreate执行时的this。 onCreate执行的是patch里的方法，这时的class name是带_CF后缀的。  
关键点是 执行被替换掉的方法的过程中，获得的class上下文信息，也应该是 原有方法的。

**Comment by THEONE10211024** [comment]
@JuanbingTeam 这个问题你解决了吗？是不是只在Art上有问题？

**Comment by JuanbingTeam** [comment]
@THEONE10211024  最近比较忙，没有跟进测试。 当时的问题是不止 ART的。

这个问题可以避免，尽量将大方法抽成小的函数就能避免此类问题了。

**Comment by liericiyan** [comment]
怎么解决啊？

**Comment by zhjkenneth** [comment]
我也遇到了java.lang.NoClassDefFoundError，然后报X.X.MainApplication_CF的错误，这时我的修改是，调用`PatchManager patchManager = new PatchManager(this);
        patchManager.init("1.0.0");
        patchManager.loadPatch();`在Application子类的onCreate前执行，addPath方法在一个Activity错误前调用。测试结果通过了，手机是华为3X，系统Android 4.3；moto X,系统 5.1.1
