### ISSUE TITLE
不支持内部類？

### ISSUE THREAD

**Issue by linving** [alibaba/AndFix#280]
不支持内部類？

**Comment by wziwen** [comment]
java.lang.IllegalAccessError: Illegal class access: 'com.xinjudian.juju.pub.IndexAct_CF' attempting to access 'com.xinjudian.juju.pub.IndexAct$1' (declaration of 'com.xinjudian.juju.pub.IndexAct_CF' appears in /data/user/0/com.zdnst.jujuplus/files/apatch/juju.apatch)
                                                     at com.xinjudian.juju.pub.IndexAct_CF.initView(IndexAct.java:59)
                                                     at com.xinjudian.juju.common.BaseAct.onCreate(BaseAct.java:81)
                                                     at android.app.Activity.performCreate(Activity.java:6664)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

7.0 的虚拟机上报错, 6.0 真机上不会

**Comment by surahul** [comment]
I am also getting the same issue 
Stack trace : 
Fatal Exception: java.lang.IllegalAccessError: Illegal class access: 'com.rahul.videoderbeta.ads.b_CF' attempting to access 'com.rahul.videoderbeta.ads.e' (declaration of 'com.rahul.videoderbeta.ads.b_CF' appears in /data/user/0/com.rahul.videoderbeta/files/apatch/12.0.4.apatch)
       at com.rahul.videoderbeta.ads.b_CF.a(SourceFile:63)
       at com.rahul.videoderbeta.ads.CustomAdRenderer.renderAdView(SourceFile:49)
       at com.rahul.videoderbeta.ads.CustomNativeAd.renderAdView(SourceFile:138)
       at com.rahul.videoderbeta.adsnew.model.OtherNativeAd.displayAdOnView(SourceFile:25)
       at com.rahul.videoderbeta.mediadetail.viewholders.AdViewHolder.bind(SourceFile:29)
       at com.rahul.videoderbeta.mediadetail.MediaDetailMiniAdapter.onBindViewHolder(SourceFile:139)
       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(SourceFile:5825)
       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(SourceFile:5858)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:5094)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(SourceFile:4970)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(SourceFile:2029)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(SourceFile:1414)
       at android.support.v7.widget.LinearLayoutManager.fill(SourceFile:1377)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(SourceFile:578)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(SourceFile:3315)
       at android.support.v7.widget.RecyclerView.onMeasure(SourceFile:2843)
       at android.view.View.measure(View.java:20986)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6447)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:20986)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6447)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
       at android.view.View.measure(View.java:20986)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6447)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
       at android.view.View.measure(View.java:20986)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6447)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(SourceFile:700)
       at android.support.design.widget.CoordinatorLayout.onMeasure(SourceFile:767)
       at android.view.View.measure(View.java:20986)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6447)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:20986)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
       at android.view.View.measure(View.java:20986)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6447)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:20986)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
       at android.view.View.measure(View.java:20986)
       at android.support.v4.widget.DrawerLayout.onMeasure(SourceFile:1085)
       at android.view.View.measure(View.java:20986)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6447)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(SourceFile:135)
       at android.view.View.measure(View.java:20986)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6447)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:20986)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6447)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:20986)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6447)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
       at android.view.View.measure(View.java:20986)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6447)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:771)
       at android.view.View.measure(View.java:20986)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2508)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1575)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1824)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6895)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:924)
       at android.view.Choreographer.doCallbacks(Choreographer.java:699)
       at android.view.Choreographer.doFrame(Choreographer.java:635)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:910)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6640)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
