### ISSUE TITLE
addPatch  java.util.zip.ZipException: File too short to be a zip file: 0

### ISSUE THREAD

**Issue by hehr** [alibaba/AndFix#281]
差分包打进去之后，修补的时候抛这个异常是因为什么？

**Comment by hehr** [comment]
这里是log ,我的pach包打出来大小只有2k大小，这个是正常的吗？
11-10 12:29:42.481 15208-15458/test.hehr.org.andfixtest E/Surface: getSlotFromBufferLocked: unknown buffer: 0xa89b1fe0
11-10 12:29:47.620 15208-15458/test.hehr.org.andfixtest E/Surface: getSlotFromBufferLocked: unknown buffer: 0xa89b2030
11-10 12:29:51.047 18128-18128/test.hehr.org.andfixtest D/AndFix: vm is: art , apilevel is: 23
11-10 12:29:51.058 18128-18128/test.hehr.org.andfixtest E/PatchManager: addPatch
                                                                        java.util.zip.ZipException: File too short to be a zip file: 0
                                                                            at java.util.zip.ZipFile.readCentralDir(ZipFile.java:388)
                                                                            at java.util.zip.ZipFile.<init>(ZipFile.java:175)
                                                                            at java.util.jar.JarFile.<init>(JarFile.java:199)
                                                                            at java.util.jar.JarFile.<init>(JarFile.java:182)
                                                                            at java.util.jar.JarFile.<init>(JarFile.java:168)
                                                                            at com.alipay.euler.andfix.patch.Patch.init(Patch.java:75)
                                                                            at com.alipay.euler.andfix.patch.Patch.<init>(Patch.java:67)
                                                                            at com.alipay.euler.andfix.patch.PatchManager.addPatch(PatchManager.java:126)
                                                                            at com.alipay.euler.andfix.patch.PatchManager.initPatchs(PatchManager.java:112)
                                                                            at com.alipay.euler.andfix.patch.PatchManager.init(PatchManager.java:105)
                                                                            at test.hehr.org.andfixtest.AndfixApplication.onCreate(AndfixApplication.java:28)
                                                                            at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:369)
                                                                            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                                            at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-10 12:29:51.058 18128-18128/test.hehr.org.andfixtest E/AndfixApplication: inited.
11-10 12:29:51.059 18128-18128/test.hehr.org.andfixtest E/AndfixApplication: apatch loaded.
11-10 12:29:51.061 18128-18128/test.hehr.org.andfixtest D/PatchManager: patch [/storage/emulated/0/out.apatch] has be loaded.
11-10 12:29:51.061 18128-18128/test.hehr.org.andfixtest E/AndfixApplication: apatch:/storage/emulated/0/out.apatch added.
11-10 12:29:51.238 18128-18128/test.hehr.org.andfixtest W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable

**Comment by hehr** [comment]
./apkpatch.sh  -f bug-fix.apk  -t  bug.apk  -o output  -k   keystore_path  - p storePassword   -a  keyAlias   -e   keyPassword

**Comment by hehr** [comment]
查出来，问题是6.0上面读取权限问题才有这个问题。但是我在application onCreate()去调用addpatch()不生效。。。。

**Comment by hehr** [comment]
11-10 16:33:49.183 29723-29723/test.hehr.org.andfixtest W/linker: /system/lib64/libfilterUtils.so: unused DT entry: type 0x6ffffffe arg 0x808
11-10 16:33:49.183 29723-29723/test.hehr.org.andfixtest W/linker: /system/lib64/libfilterUtils.so: unused DT entry: type 0x6fffffff arg 0x2
11-10 16:33:49.191 29723-29723/test.hehr.org.andfixtest D/FlymeTrafficTracking: tag  (29) test.hehr.org.andfixtest main uid 10145
11-10 16:33:49.192 29723-29723/test.hehr.org.andfixtest D/NetworkManagementSocketTagger: tagSocket(29) with statsTag=0xffffffff, statsUid=-1
11-10 16:33:49.198 29723-29723/test.hehr.org.andfixtest W/linker: /data/app/test.hehr.org.andfixtest-1/lib/arm64/libandfix.so: unused DT entry: type 0x6ffffffe arg 0xb08
11-10 16:33:49.198 29723-29723/test.hehr.org.andfixtest W/linker: /data/app/test.hehr.org.andfixtest-1/lib/arm64/libandfix.so: unused DT entry: type 0x6fffffff arg 0x2
11-10 16:33:49.199 29723-29723/test.hehr.org.andfixtest D/AndFix: vm is: art , apilevel is: 22
11-10 16:33:49.202 29723-29723/test.hehr.org.andfixtest D/OpenSSLLib: OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:145;Function:ASN1_get_object
11-10 16:33:49.213 29723-29723/test.hehr.org.andfixtest D/OpenSSLLib: OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:145;Function:ASN1_get_object
11-10 16:33:49.220 29723-29723/test.hehr.org.andfixtest E/AndfixApplication: inited.
11-10 16:33:49.223 29723-29723/test.hehr.org.andfixtest D/OpenSSLLib: OpensslErr:Module:13(114:155); file:external/openssl/crypto/asn1/asn1_lib.c ;Line:145;Function:ASN1_get_object
11-10 16:33:49.232 29723-29723/test.hehr.org.andfixtest E/AndfixApplication: apatch loaded.
11-10 16:33:49.232 29723-29723/test.hehr.org.andfixtest E/AndfixApplication: patchFileString: /storage/emulated/0/out.apatch
11-10 16:33:49.232 29723-29723/test.hehr.org.andfixtest D/PatchManager: patch [/storage/emulated/0/out.apatch] has be loaded.
11-10 16:33:49.232 29723-29723/test.hehr.org.andfixtest E/AndfixApplication: apatch:/storage/emulated/0/out.apatch added.
11-10 16:33:49.232 29723-29723/test.hehr.org.andfixtest D/ActivityThread: BIND_APPLICATION handled : 0 / AppBindData{appInfo=ApplicationInfo{1282a0d6 test.hehr.org.andfixtest}}
11-10 16:33:49.233 29723-29723/test.hehr.org.andfixtest V/ActivityThread: Handling launch of ActivityRecord{2a23df57 token=android.os.BinderProxy@339cca44 {test.hehr.org.andfixtest/test.hehr.org.andfixtest.MainActivity}}
11-10 16:33:49.344 29723-29723/test.hehr.org.andfixtest V/ActivityThread: ActivityRecord{2a23df57 token=android.os.BinderProxy@339cca44 {test.hehr.org.andfixtest/test.hehr.org.andfixtest.MainActivity}}: app=test.hehr.org.andfixtest.AndfixApplication@17dff462, appName=test.hehr.org.andfixtest, pkg=test.hehr.org.andfixtest, comp={test.hehr.org.andfixtest/test.hehr.org.andfixtest.MainActivity}, dir=/data/app/test.hehr.org.andfixtest-1/base.apk
11-10 16:33:49.449 29723-29723/test.hehr.org.andfixtest W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
