### ISSUE TITLE
一打补丁就报failure in processEncodedAnnotation错误

### ISSUE THREAD

**Issue by qzsang** [alibaba/AndFix#282]
一打补丁就报这个错

 Process: com.example.administrator.andfixtest, PID: 17499
                                                   java.lang.RuntimeException: failure in processEncodedAnnotation
                                                       at java.lang.reflect.Method.getAnnotation(Native Method)
                                                       at java.lang.reflect.Method.getAnnotation(Method.java:266)
                                                       at com.alipay.euler.andfix.AndFixManager.fixClass(SourceFile:199)
                                                       at com.alipay.euler.andfix.AndFixManager.fix(SourceFile:179)
                                                       at com.alipay.euler.andfix.a.b.a(SourceFile:238)
                                                       at com.alipay.euler.andfix.a.b.b(SourceFile:165)
                                                       at com.example.administrator.andfixtest.h.run(SourceFile:59)
                                                       at java.lang.Thread.run(Thread.java:841)

是我哪里配置错了吗

**Comment by qzsang** [comment]
用0.3.1  不混淆是正常的   ，一混淆就这个错，0.5.0  不混淆也是这个错
