### ISSUE TITLE
Signature was not verified

### ISSUE THREAD

**Issue by nielev** [alibaba/AndFix#283]
我明明是用正确的keystore打出的patch文件,为什么还是会报签名未验证的错误`java.security.SignatureException: Signature was not verified
                                                        at org.apache.harmony.security.provider.cert.X509CertImpl.verify(X509CertImpl.java:378)
                                                        at com.alipay.euler.andfix.security.SecurityChecker.check(SecurityChecker.java:158)
                                                        at com.alipay.euler.andfix.security.SecurityChecker.verifyApk(SecurityChecker.java:124)
                                                        at com.alipay.euler.andfix.AndFixManager.fix(AndFixManager.java:127)
                                                        at com.alipay.euler.andfix.patch.PatchManager.loadPatch(PatchManager.java:214)
                                                        at com.oray.sunlogin.application.SunloginApplication.initAndfix(SunloginApplication.java:103)
                                                        at com.oray.sunlogin.application.SunloginApplication.onCreate(SunloginApplication.java:90)
                                                        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4355)
                                                        at android.app.ActivityThread.access$1500(ActivityThread.java:139)
                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1270)
                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                        at android.os.Looper.loop(Looper.java:136)
                                                        at android.app.ActivityThread.main(ActivityThread.java:5028)
                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
                                                        at dalvik.system.NativeStart.main(Native Method)`

**Comment by nielev** [comment]
我查了一下patch文件，和安装的apk，和keystore的证书指纹，都是一模一样的，为什么还是会报这个错？

**Comment by nielev** [comment]
尴尬permission没加<uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"/>

**Comment by nielev** [comment]
``<uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"/>
