### ISSUE TITLE
生成patch报错

### ISSUE THREAD

**Issue by shidongdi** [alibaba/AndFix#284]
只修改2行代码（不涉及资源文件），却发现如下改动，未能生成patch包：
add modified Method:Landroid/graphics/drawable/Drawable;  newDrawable()  in Class:Landroid/support/a/a/b$a;
add modified Method:Landroid/graphics/drawable/Drawable;  newDrawable(Landroid/content/res/Resources;)  
in Class:Landroid/support/a/a/b$a;
add modified Method:V  inflate(Landroid/content/res/Resources;Lorg/xmlpull/v1/XmlPullParser;
Landroid/util/AttributeSet;Landroid/content/res/Resources$Theme;)  
in Class:Landroid/support/a/a/b;
add modified Method:Z  isAutoMirrored()  in Class:Landroid/support/a/a/b;
add modified Method:V  setAutoMirrored(Z)  in Class:Landroid/support/a/a/b;
add modified Method:V  a(Landroid/graphics/Path;DDDDDDDDD)  in Class:Landroid/support/a/a/d$b;
add modified Method:Landroid/support/a/a/g;  a(Landroid/content/res/Resources;
ILandroid/content/res/Resources$Theme;)  in Class:Landroid/support/a/a/g;
add modified Method:Z  a()  in Class:Landroid/support/a/a/g;
add modified Method:V  b(Landroid/content/res/Resources;Lorg/xmlpull/v1/XmlPullParser;
Landroid/util/AttributeSet;Landroid/content/res/Resources$Theme;)  
in Class:Landroid/support/a/a/g;
add modified Method:Z  isAutoMirrored()  in Class:Landroid/support/a/a/g;
add modified Method:V  setAutoMirrored(Z)  in Class:Landroid/support/a/a/g;
java.lang.RuntimeException: can,t modified Field:abc_background_cache_hint_selector_material_dark(I), 
in class :Landroid/support/design/R$color;
        at com.euler.patch.diff.DiffInfo.addModifiedFields(DiffInfo.java:88)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:125)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:101)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:95)
        at com.euler.patch.diff.DexDiffer.diff(DexDiffer.java:32)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:68)
        at com.euler.patch.Main.main(Main.java:97)

--
依赖里面有些用到'com.android.support:appcompat-v7:+'这种的，怀疑依赖版本不一致导致的？望解答，谢谢！

**Comment by huaye800000** [comment]
遇到同样的问题：
java.lang.RuntimeException: can,t modified Field:abc_background_cache_hint_selector_material_dark(I), in class :Landroid/support/design/R$color;
        at com.euler.patch.diff.DiffInfo.addModifiedFields(DiffInfo.java:88)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:125)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:101)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:95)
        at com.euler.patch.diff.DexDiffer.diff(DexDiffer.java:32)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:68)
        at com.euler.patch.Main.main(Main.java:97)
你是怎么解决这个问题的？求指点

**Comment by shidongdi** [comment]
忘记了，已经弃用andfix改成Tinker了。andfix限制太多 @huaye800000

**Comment by huaye800000** [comment]
谢谢指导。
