### ISSUE TITLE
混淆之后，apkpatch的时候出现java.lang.RuntimeException

### ISSUE THREAD

**Issue by cock-tail** [alibaba/AndFix#29]
没混淆之前是没有问题的，但增加了混淆之后就出现异常
``` 
-keep class com.alipay.euler.andfix.AndFix { *; }
-keep class com.alipay.euler.andfix.annotation.MethodReplace { *; }
-keep class * extends java.lang.annotation.Annotation
-keepclasseswithmembernames class * {
    native <methods>;
} 
```
是我操作出现了问题了吗？   这个问题搞了好久，求帮助

异常信息：
```
java.lang.RuntimeException: can,t add new Field:a(I), in class :Lcom/euler/a/a;
	at com.euler.patch.diff.DiffInfo.addAddedFields(DiffInfo.java:77)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:132)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:101)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:95)
	at com.euler.patch.diff.DexDiffer.diff(DexDiffer.java:32)
	at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:68)
	at com.euler.patch.Main.main(Main.java:97)
```

**Comment by JuanbingTeam** [comment]
不支持 新加的field

**Comment by cock-tail** [comment]
我也没有新加field，我使用的就是demo，只是将demo增加了混淆，没混淆之前是可以的。。。
现在混淆之后apkpatch倒是可以的（增加了-applymapping），但是加入out.apatch运行demo就出问题了
@JuanbingTeam

**Comment by supern** [comment]
MainActivity有修改？

**Comment by cock-tail** [comment]
@supern 没有，我只改了A.java

**Comment by cock-tail** [comment]
@supern 

**未混淆**，apkpatch：
```
add modified Method:V  <init>()  in Class:Lcom/euler/test/A;
add modified Method:Ljava/lang/String;  a(Ljava/lang/String;)  in Class:Lcom/euler/test/A;
add modified Method:I  b(Ljava/lang/String;Ljava/lang/String;)  in Class:Lcom/euler/test/A;
```
**混淆之后**，apkpatch：
```
add modified Method:V  <init>()  in Class:Lcom/euler/a/a;
add new Method:Ljava/lang/String;  a(Ljava/lang/String;)  in Class:Lcom/euler/a/a;
add new Method:I  b(Ljava/lang/String;)  in Class:Lcom/euler/a/a;
add modified Method:V  onCreate(Landroid/os/Bundle;)  in Class:Lcom/euler/andfix
```

**反编译APK**
1.APK：MainActivity
```
public class MainActivity extends Activity {
    public void onCreate(Bundle bundle) {
        super.onCreate(bundle);
        Log.e("euler", a.a());
        StringBuilder stringBuilder = new StringBuilder();
        a aVar = new a();
        Log.e("euler", stringBuilder.append(a.b()).toString());
        stringBuilder = new StringBuilder();
        aVar = new a();
        Log.e("euler", stringBuilder.append(a.c()).toString());
    }

    protected void onDestroy() {
        super.onDestroy();
        Process.killProcess(Process.myPid());
    }
}
```

2.apk:MainActivity
```
public class MainActivity extends Activity {
    public void onCreate(Bundle bundle) {
        super.onCreate(bundle);
        Log.e("euler", a.a());
        StringBuilder stringBuilder = new StringBuilder();
        a aVar = new a();
        Log.e("euler", stringBuilder.append(a.b()).toString());
        stringBuilder = new StringBuilder();
        aVar = new a();
        Log.e("euler", stringBuilder.append(a.c()).toString());
    }

    protected void onDestroy() {
        super.onDestroy();
        Process.killProcess(Process.myPid());
    }
}
```

**Comment by cock-tail** [comment]
我发现有没有混淆，经过apkpatch后的diff.dex文件里面有些不同

**混淆** diff.dex:有两个文件分别是a_CF和MainAcivity_CF
```
package com.euler.a;

import android.util.Log;

/* compiled from: A */
public final class a_CF {
    static int b;

    static {
        b = 10;
    }

    public static String a(String str) {
        return c.a(str);
    }

    public static int b(String str) {
        c cVar = new c();
        Log.e("euler", str);
        Log.e("euler", c.c + "==" + c.a());
        Log.i("euler", "fix succes" + cVar.a);
        Log.i("euler", c.b.a);
        return 0;
    }

    public static int c() {
        return a.b;
    }
}
```
```
package com.euler.andfix;

import android.app.Activity;
import android.os.Bundle;
import android.os.Process;
import android.util.Log;
import com.alipay.euler.andfix.annotation.MethodReplace;
import com.euler.a.a;
import com.euler.a.a_CF;

/* compiled from: MainActivity */
public class MainActivity_CF extends Activity {
    @MethodReplace(clazz = "com.euler.andfix.MainActivity", method = "onCreate")
    public void onCreate(Bundle bundle) {
        super.onCreate(bundle);
        Log.e("euler", a_CF.a("good"));
        StringBuilder stringBuilder = new StringBuilder();
        a com_euler_a_a_CF = new a_CF();
        Log.e("euler", stringBuilder.append(a_CF.b("s1")).toString());
        stringBuilder = new StringBuilder();
        com_euler_a_a_CF = new a_CF();
        Log.e("euler", stringBuilder.append(a_CF.c()).toString());
    }

    protected void onDestroy() {
        super.onDestroy();
        Process.killProcess(Process.myPid());
    }
}
```

**未混淆** 只有一个文件A_CF
```
package com.euler.test;

import com.alipay.euler.andfix.annotation.MethodReplace;

/* compiled from: A */
public class A_CF {
    static int i;

    static {
        i = 10;
    }

    @MethodReplace(clazz = "com.euler.test.A", method = "a")
    public static String a(String str) {
        return Fix.a(str);
    }

    @MethodReplace(clazz = "com.euler.test.A", method = "b")
    public int b(String s1, String s2) {
        return new Fix().b(s1, s2);
    }

    public int getI() {
        return A.i;
    }
}
```

区别在于@MethodReplace这个，然后我就将A和Fix这个两个类不混淆
```
 -keep class com.euler.test.A {*;}
-keep class com.euler.test.Fix {*;} 
```
重新来一遍，果然没有问题。

我不知道是不是我混淆有问题，还是AndFix存在这个问题，如果每次要修改的关联的类不能混淆的话，这感觉不太好。。。

注：AndFix我是作为一个module
最后附上我的混淆：
```
# To enable ProGuard in your project, edit project.properties
# to define the proguard.config property as described in that file.
#
# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in ${sdk.dir}/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the ProGuard
# include property in project.properties.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}
##--- For:android默认 ---
-optimizationpasses 5  # 指定代码的压缩级别
-allowaccessmodification #优化时允许访问并修改有修饰符的类和类的成员
-dontusemixedcaseclassnames  # 是否使用大小写混合
-dontskipnonpubliclibraryclasses  # 是否混淆第三方jar
-dontpreverify  # 混淆时是否做预校验
-verbose    # 混淆时是否记录日志
-ignorewarnings  # 忽略警告，避免打包时某些警告出现
-optimizations !code/simplification/arithmetic,!code/simplification/cast,!field/*,!class/merging/*  # 混淆时所采用的算法

-keepattributes *Annotation*
-keep public class com.google.vending.licensing.ILicensingService
-keep public class com.android.vending.licensing.ILicensingService
-keepclasseswithmembernames class * { # 保持 native 方法不被混淆
    native <methods>;
}

-keepclassmembers public class * extends android.view.View {
   void set*(***);
   *** get*();
}

-keepclassmembers class * extends android.app.Activity {
   public void *(android.view.View);
}

-keepclassmembers enum * {  # 保持枚举 enum 类不被混淆
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

-keep class * implements android.os.Parcelable { # 保持 Parcelable 不被混淆
  public static final android.os.Parcelable$Creator *;
}

-keepclassmembers class **.R$* { #不混淆R文件
    public static <fields>;
}

-dontwarn android.support.**
##--- End android默认 ---

##--- For:不能被混淆的 ---
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Fragment
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.app.backup.BackupAgentHelper
-keep public class * extends android.preference.Preference

##--- For:保持自定义控件类不被混淆 ---
-keepclasseswithmembers class * {
    public <init>(android.content.Context, android.util.AttributeSet);
}
-keepclasseswithmembers class * {
    public <init>(android.content.Context, android.util.AttributeSet, int);
}
##--- For:android-support-v4 ---
-dontwarn android.support.v4.**
-keep class android.support.v4.** { *; }
-keep interface android.support.v4.app.** { *; }
-keep class * extends android.support.v4.** { *; }
-keep public class * extends android.support.v4.**
-keep public class * extends android.support.v4.widget
-keep class * extends android.support.v4.app.** {*;}
-keep class * extends android.support.v4.view.** {*;}

##--- For:Serializable ---
-keep class * implements java.io.Serializable {*;}
-keepnames class * implements java.io.Serializable
-keepclassmembers class * implements java.io.Serializable {*;}

##--- For:Gson ---
-keepattributes *Annotation*
-keep class sun.misc.Unsafe { *; }
-keep class com.idea.fifaalarmclock.entity.***
-keep class com.google.gson.stream.** { *; }
-keepattributes *Annotation* #使用注解
-keepattributes Signature #过滤泛型  出现类型转换错误时，启用这个
-keepattributes SourceFile,LineNumberTable

##  For: AndFix
-keep class com.alipay.euler.andfix.AndFix { *; }
-keep class com.alipay.euler.andfix.annotation.MethodReplace { *; }
-keep class * extends java.lang.annotation.Annotation
-keepclasseswithmembernames class * {
    native <methods>;
}

-keep class com.euler.test.A {*;}
-keep class com.euler.test.Fix {*;}

-applymapping /Users/admin/Desktop/mapping1.txt
```

**Comment by gdgm123** [comment]
@cock-tail AndFix的所有代码都不能混淆

**Comment by cock-tail** [comment]
我试过了，没什么用
```
-keep class com.alipay.euler.andfix.** {*;}
```
@gdgm123

**Comment by supern** [comment]
@cock-tail 可以把你混淆后的两个apk发我下么，我看下是不是apkpatch的问题

**Comment by cock-tail** [comment]
已发送到你的gmail邮箱@supern

**Comment by supern** [comment]
@cock-tail  apk混淆要使用相同的字典mapping.txt

Code Protection

In order to achieve Code Protection,you might have used some techniques such as below:

ProGuard

you must save the mapping.txt, so your new version's build can use it with "-applymapping".

http://proguard.sourceforge.net/manual/usage.html#applymapping

**Comment by birdman2005** [comment]
@supern 工具打差分包的时候，为何在我的activity后面加了个_CF?

**Comment by dmh15454223** [comment]
兄弟，最后如何解决了？我现在也碰到了这个问题。

**Comment by huxin123** [comment]
这个问题最后解决了没有啊 ？ 我发现是使用了MultiDex之后就apkpatch报错了

**Comment by huxin123** [comment]
@supern   这个问题最后解决了没有啊 ？ 我发现是使用了MultiDex之后就apkpatch报错了

**Comment by cokepanm** [comment]
AndFix不支持MultiDex，参考#112解决

**Comment by sldboy** [comment]
我的混淆包进行apkpatch的时候也是出这个错误.作者怎么解决啊?

**Comment by dmh15454223** [comment]
你好，你是哪位？








在 2016-04-12 18:14:59，"sldboy" <notifications@github.com> 写道：


我的混淆包进行apkpatch的时候也是出这个错误.作者怎么解决啊?

**Comment by landryshuai** [comment]
@supern 我的混淆包进行apkpatch的时候, 发现 @MethodReplace里面备注的class会存在问题。请问该怎么解决？

**Comment by anzyhui** [comment]
有可能是，你的bug版本中，没有调用方法a，所以不会被打包进dex中，而修复bug后的版本中，调用了方法a。在打出的差分包应用于bug版本中时，在bug版本中找不到a方法，无法替换，所以报错。
