### ISSUE TITLE
就随便加的语句，就崩溃了

### ISSUE THREAD

**Issue by atxxiang3** [alibaba/AndFix#290]
FATAL EXCEPTION: main
                                                   Process: com.tts.hybird, PID: 11691
                                                   java.lang.IllegalAccessError: Illegal class access: 'com.tts.ct_trip.home.BusTicketActivity_CF' attempting to access 'com.tts.ct_trip.home.BusTicketActivity$3' (declaration of 'com.tts.ct_trip.home.BusTicketActivity_CF' appears in /data/user/0/com.tts.hybird/files/apatch/2-ca5b66cef98a21e32d04247c69a87677.apatch)
                                                       at com.tts.ct_trip.home.BusTicketActivity_CF.onCreate(BusTicketActivity.java:2385)
                                                       at android.app.Activity.performCreate(Activity.java:6664)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                       at android.app.ActivityThread.startActivityNow(ActivityThread.java:2446)
                                                       at android.app.LocalActivityManager.moveToState(LocalActivityManager.java:136)
                                                       at android.app.LocalActivityManager.startActivity(LocalActivityManager.java:348)
                                                       at android.widget.TabHost$IntentContentStrategy.getContentView(TabHost.java:724)
                                                       at android.widget.TabHost.setCurrentTab(TabHost.java:388)
                                                       at android.widget.TabHost.addTab(TabHost.java:222)
                                                       at com.tts.ct_trip.HomeActivity.a(HomeActivity.java:317)
                                                       at com.tts.ct_trip.HomeActivity.onCreate(HomeActivity.java:150)
                                                       at android.app.Activity.performCreate(Activity.java:6664)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by zhaobenbing** [comment]
楼主解决了吗，我也是，添加一个简单的语句直接crash
