### ISSUE TITLE
求教 首次加载补丁是没问题的，再次加载补丁程序就会闪退，但是补丁也是加载成功的

### ISSUE THREAD

**Issue by LiduForAndroid** [alibaba/AndFix#293]
![qq 20161125143416](https://cloud.githubusercontent.com/assets/24238123/20693778/98e31550-b61b-11e6-85ef-b49d7893ad59.png)
![qq 20161125150610](https://cloud.githubusercontent.com/assets/24238123/20693783/9eb0ba50-b61b-11e6-9c25-5c35dc4f8909.png)

**Comment by LihtXX** [comment]
我也是这样，第一次修复，正常，修复了，再点一次，就崩了
     Process: com.example.admin.constraintlayoutdemo, PID: 8942
                                                                                      java.lang.NoSuchFieldError: No instance field patchManager of type Lcom/alipay/euler/andfix/patch/PatchManager; in class Lcom/example/admin/constraintlayoutdemo/MyApplication; or its superclasses (declaration of 'com.example.admin.constraintlayoutdemo.MyApplication' appears in /data/app/com.example.admin.constraintlayoutdemo-1/base.apk)
                                                                                          at com.example.admin.constraintlayoutdemo.MainActivity_CF.onClick(MainActivity.java:52)
                                                                                          at android.view.View.performClick(View.java:4809)
                                                                                          at android.view.View$PerformClick.run(View.java:20123)
                                                                                          at android.os.Handler.handleCallback(Handler.java:815)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                          at android.os.Looper.loop(Looper.java:194)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5536)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

**Comment by LihtXX** [comment]
为啥

**Comment by LBJ6666** [comment]
我也是这样，第一次修复，正常，修复了，再点一次，就崩了，为啥
     Process: com.example.admin.constraintlayoutdemo, PID: 8942
                                                                                      java.lang.NoSuchFieldError: No instance field patchManager of type Lcom/alipay/euler/andfix/patch/PatchManager; in class Lcom/example/admin/constraintlayoutdemo/MyApplication; or its superclasses (declaration of 'com.example.admin.constraintlayoutdemo.MyApplication' appears in /data/app/com.example.admin.constraintlayoutdemo-1/base.apk)
                                                                                          at com.example.admin.constraintlayoutdemo.MainActivity_CF.onClick(MainActivity.java:52)
                                                                                          at android.view.View.performClick(View.java:4809)
                                                                                          at android.view.View$PerformClick.run(View.java:20123)
                                                                                          at android.os.Handler.handleCallback(Handler.java:815)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                          at android.os.Looper.loop(Looper.java:194)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5536)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
