### ISSUE TITLE
java.util.zip.ZipException: File too short to be a zip file: 0

### ISSUE THREAD

**Issue by guozhyuan** [alibaba/AndFix#294]
手机:Nexus5X 7.0
版本:0.3.1
其他:在小米4.4上运行正常
异常:
```
E/PatchManager: addPatch
                                                 java.util.zip.ZipException: File too short to be a zip file: 0
                                                     at java.util.zip.ZipFile.<init>(ZipFile.java:208)
                                                     at java.util.zip.ZipFile.<init>(ZipFile.java:147)
                                                     at java.util.jar.JarFile.<init>(JarFile.java:161)
                                                     at java.util.jar.JarFile.<init>(JarFile.java:125)
                                                     at com.alipay.euler.andfix.patch.Patch.init(Patch.java:75)
                                                     at com.alipay.euler.andfix.patch.Patch.<init>(Patch.java:67)
                                                     at com.alipay.euler.andfix.patch.PatchManager.addPatch(PatchManager.java:126)
                                                     at com.alipay.euler.andfix.patch.PatchManager.initPatchs(PatchManager.java:112)
                                                     at com.alipay.euler.andfix.patch.PatchManager.init(PatchManager.java:105)
                                                     at g.andfix.com.andfix.MainActivity.onCreate(MainActivity.java:36)
                                                     at android.app.Activity.performCreate(Activity.java:6664)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by qinhaichao88** [comment]
你应该是没有添加读写sdcard的权限吧

**Comment by ikhanal** [comment]
Did you solve this problem?
