### ISSUE TITLE
引入anfix的会导致 couldn't find "libpl_droidsonroids_gif.so"

### ISSUE THREAD

**Issue by ZWPDean** [alibaba/AndFix#298]
工程中导入了gif.jar，在导入anfix后会报
 java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader［...nativeLibraryDirectories=[/data/app/com.aibasis.xiaole_chat-1/lib/arm64, /vendor/lib64, /system/lib64, /vendor/lib64, /system/lib64]]] couldn't find "libpl_droidsonroids_gif.so"
 at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                          at java.lang.System.loadLibrary(System.java:988)
                                                                          at pl.droidsonroids.gif.GifInfoHandle.<clinit>(GifInfoHandle.java:40)
                                                                          at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:150)
                                                                          at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:100)
                                                                      	at com.aibasis.xiaole_chat.util.Gif.displayGif

**Comment by ZWPDean** [comment]
之前有人都提过相似的问题，可以通过
* ndk {
abiFilters "armeabi", "x86"
}*
设置自己支持的系统框架或者给所有jar包添加缺失的框架.so文件
