### ISSUE TITLE
java.io.IOException: unable to open DEX file

### ISSUE THREAD

**Issue by w4lle** [alibaba/AndFix#30]
09-25 15:09:33.845  29850-29850/com.euler.andfix D/euler﹕ inited.
09-25 15:09:33.845  29850-29850/com.euler.andfix D/SecurityChecker﹕ mDebuggable = true
09-25 15:09:33.850  29850-29850/com.euler.andfix I/dalvikvm﹕ Zip is good, but no classes.dex inside, and no valid .odex file in the same directory
09-25 15:09:33.860  29850-29850/com.euler.andfix D/dalvikvm﹕ GC_FOR_ALLOC freed 402K, 3% free 14725K/15160K, paused 13ms, total 13ms
09-25 15:09:33.860  29850-29850/com.euler.andfix E/AndFixManager﹕ pacth
    java.io.IOException: unable to open DEX file
            at dalvik.system.DexFile.openDexFileNative(Native Method)
            at dalvik.system.DexFile.openDexFile(DexFile.java:296)
            at dalvik.system.DexFile.<init>(DexFile.java:111)
            at dalvik.system.DexFile.loadDex(DexFile.java:151)
            at com.alipay.euler.andfix.AndFixManager.fix(AndFixManager.java:147)
            at com.alipay.euler.andfix.patch.PatchManager.loadPatch(PatchManager.java:214)
            at com.euler.andfix.MainApplication.onCreate(MainApplication.java:52)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1019)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4381)
            at android.app.ActivityThread.access$1500(ActivityThread.java:138)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1295)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5054)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
09-25 15:09:33.860  29850-29850/com.euler.andfix D/euler﹕ apatch loaded.
09-25 15:09:33.865  29850-29850/com.euler.andfix D/PatchManager﹕ patch [/storage/emulated/0/out.apatch] has be loaded.
09-25 15:09:33.865  29850-29850/com.euler.andfix D/euler﹕ apatch:/storage/emulated/0/out.apatch added.

**Comment by supern** [comment]
@w4lle .apatch file was bad,clean out your data on the device/emulator,or re-generate .apatch.

**Comment by w4lle** [comment]
rm /storage/emulated/0/out.aptach
rm /sdcard/out.apatch
uninstall the app
resolved.

**Comment by selmon** [comment]
.apatch file was bad, re-generate this file one more time
