### ISSUE TITLE
打补丁失败，尝试了很多次都是这样

### ISSUE THREAD

**Issue by androidLG** [alibaba/AndFix#301]
java.lang.RuntimeException: can,t modified Field:design_bottom_sheet_slide_in(I), in class :Landroid/support/design/R$anim;
	at com.euler.patch.diff.DiffInfo.addModifiedFields(DiffInfo.java:88)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:125)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:101)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:95)
	at com.euler.patch.diff.DexDiffer.diff(DexDiffer.java:32)
	at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:68)
	at com.euler.patch.Main.main(Main.java:97)

**Comment by gsrRose** [comment]
你是做了什么改动？，活人好少啊，相互解决吧

**Comment by supern** [comment]
不支持修改资源
