### ISSUE TITLE
java.lang.IncompatibleClassChangeError: android/content/SharedPreferences$Editor

### ISSUE THREAD

**Issue by canmeizhexue** [alibaba/AndFix#309]
红米note 1s，一运行就崩溃，

12-22 10:05:42.238 17815-17815/com.euler.andfix D/ActivityThread: setTargetHeapUtilization:0.75
12-22 10:05:42.238 17815-17815/com.euler.andfix D/ActivityThread: setTargetHeapMinFree:2097152
12-22 10:05:42.378 17815-17815/com.euler.andfix D/dalvikvm: Trying to load lib /data/app-lib/com.euler.andfix-1/libandfix.so 0x429506f0
12-22 10:05:42.378 17815-17815/com.euler.andfix D/dalvikvm: Added shared lib /data/app-lib/com.euler.andfix-1/libandfix.so 0x429506f0
12-22 10:05:42.378 17815-17815/com.euler.andfix D/AndFix: vm is: dalvik , apilevel is: 19
12-22 10:05:42.378 17815-17815/com.euler.andfix D/AndFix: _Z20dvmDecodeIndirectRefP6ThreadP8_jobject = 0x415a5575
12-22 10:05:42.378 17815-17815/com.euler.andfix D/AndFix: _Z13dvmThreadSelfv = 0x415ae979
12-22 10:05:42.508 17815-17815/com.euler.andfix D/euler: inited.
12-22 10:05:42.518 17815-17815/com.euler.andfix D/AndFix: modify com.euler.andfix.MainActivity.TAG flag:
12-22 10:05:42.518 17815-17815/com.euler.andfix D/AndFix: dalvik_setFieldFlag: 25 
12-22 10:05:42.518 17815-17815/com.euler.andfix D/AndFix: dalvikMethod: onCreate
12-22 10:05:42.518 17815-17815/com.euler.andfix D/AndFix: modify com.euler.andfix.MainActivity_CF.TAG flag:
12-22 10:05:42.518 17815-17815/com.euler.andfix D/AndFix: dalvik_setFieldFlag: 25 
12-22 10:05:42.528 17815-17815/com.euler.andfix D/euler: apatch loaded.
12-22 10:05:42.528 17815-17815/com.euler.andfix D/PatchManager: patch [/storage/emulated/0/out.apatch] has be loaded.
12-22 10:05:42.528 17815-17815/com.euler.andfix D/euler: apatch:/storage/emulated/0/out.apatch added.
12-22 10:05:42.528 17815-17815/com.euler.andfix D/AndroidRuntime: Shutting down VM
12-22 10:05:42.528 17815-17815/com.euler.andfix W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41cdbd58)
12-22 10:05:42.528 17815-17815/com.euler.andfix E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.euler.andfix, PID: 17815
                                                                  java.lang.IncompatibleClassChangeError: android/content/SharedPreferences$Editor
                                                                      at com.euler.andfix.MainActivity.onCreate(MainActivity.java)
                                                                      at android.app.Activity.performCreate(Activity.java:5242)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:136)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
                                                                      at dalvik.system.NativeStart.main(Native Method)
12-22 10:05:42.538 17815-17815/com.euler.andfix I/Process: Sending signal. PID: 17815 SIG: 9

**Comment by canmeizhexue** [comment]
用你们的demo,加载补丁包，一运行就报这个
