### ISSUE TITLE
unable to open DEX file

### ISSUE THREAD

**Issue by ashishkumar1000** [alibaba/AndFix#313]
Can some one tell me what is wrong? I am getting below error:

01-02 19:15:09.001 22954-22954/com.makemytrip E/dalvikvm: Unable to extract+optimize DEX from '/data/data/com.makemytrip/files/apatch/file.apatch'
01-02 19:15:09.001 22954-22954/com.makemytrip E/AndFixManager: pacth
                                                               java.io.IOException: unable to open DEX file
                                                                   at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                                   at dalvik.system.DexFile.openDexFile(DexFile.java:296)
                                                                   at dalvik.system.DexFile.<init>(DexFile.java:111)
                                                                   at dalvik.system.DexFile.loadDex(DexFile.java:151)
                                                                   at com.alipay.euler.andfix.AndFixManager.fix(AndFixManager.java:147)
                                                                   at com.alipay.euler.andfix.patch.PatchManager.loadPatch(PatchManager.java:214)
                                                                   at com.mmt.travel.app.mobile.MMTApplication.onCreate(MMTApplication.java:97)
                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)

01-02 19:15:09.001 22954-22954/com.makemytrip E/mmt_MMTApplication: XXXXX file /storage/emulated/0/file.apatch

**Comment by millerJK** [comment]
same question !! did you get answers ??

**Comment by zpp0203** [comment]
same question:Unable to instantiate application xx.MyApplication
