### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method getResources()

### ISSUE THREAD

**Issue by benjaming1314** [alibaba/AndFix#320]
java.lang.NoSuchMethodError: No virtual method getResources()Landroid/content/res/Resources; in class Lcom/lxm/ss/main/MainActivity_CF; or its super classes (declaration of 'com.lxm.ss.main.MainActivity_CF' appears in /data/data/com.lxm.ss/files/apatch/lxm_ss.apatch)
	at com.lxm.ss.main.MainActivity_CF.onClick(Unknown Source)
	at com.lxm.ss.main.MainActivity_ViewBinding$1.doClick(Unknown Source)
	at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
	at android.view.View.performClick(View.java:5155)
	at android.view.View$PerformClick.run(View.java:20747)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5835)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

这个资源没有改动怎么会找不到呢

**Comment by zSenT1100** [comment]
一样的问题，我只是改了个显示隐藏

**Comment by benjaming1314** [comment]
我把依赖包换成0.3没有这个问题，0.5问题蛮多的
