### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method

### ISSUE THREAD

**Issue by Alleeeen** [alibaba/AndFix#322]
在测试打补丁的过程中，发现如果修改的方法中有android 原生方法，如findViewById，startActivity等，打完补丁之后进入打补丁的Activity，就会报错，错误如下：
eg1; 
java.lang.NoSuchMethodError: No virtual method startActivity(Landroid/content/Intent;)V in class Lcom/netease/gameforums/ui/activity/SettingActivity_CF; or its super classes (declaration of 'com.netease.gameforums.ui.activity.SettingActivity_CF' appears in /data/user/0/com.netease.gameforums/files/apatch/315_1484141581.apatch)
	at com.netease.gameforums.ui.activity.SettingActivity_CF.j(Unknown Source)
	at com.netease.gameforums.ui.activity.SettingActivity.onClick(Unknown Source)
	at android.view.View.performClick(View.java:5273)
	at android.view.View$PerformClick.run(View.java:21315)
	at android.os.Handler.handleCallback(Handler.java:743)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)

eg2:
java.lang.NoSuchMethodError: No virtual method findViewById(I)Landroid/view/View; in class Lcom/netease/gameforums/ui/activity/SettingActivity_CF; or its super classes (declaration of 'com.netease.gameforums.ui.activity.SettingActivity_CF' appears in /data/user/0/com.netease.gameforums/files/apatch/315_1484141581.apatch)
	at com.netease.gameforums.ui.activity.SettingActivity_CF.b(Unknown Source)
	at com.netease.gameforums.ui.activity.SettingActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:6372)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539)
	at android.app.ActivityThread.access$900(ActivityThread.java:168)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)

暂时还没找到原因，有知道原因的同学麻烦说一下

**Comment by Alleeeen** [comment]
补充：0.5.0版本，
测试机子:
HUAWEI NXT-AL10，android系统6.0
Nexus 9, Android系统 7.0

**Comment by Alleeeen** [comment]
尝试改回0.4.0版本，没有该问题

**Comment by Alleeeen** [comment]
0.4.1版本也没有该问题

**Comment by iknow4x** [comment]
0.5.0版本问题很多，不建议使用，建议版本回滚。

**Comment by qinhaichao88** [comment]
我也遇到了这个问题，也是用的0.5.0， 修改android 原声的方法就会包这个错误。 
 Process: com.vivo.hotfixdemo, PID: 16434
                                                                     java.lang.NoSuchMethodError: No virtual method getPackageName()Ljava/lang/String; in class Landroid/app/Activity_CF; or its super classes (declaration of 'android.app.Activity_CF' appears in /data/user/0/com.vivo.hotfixdemo/files/apatch/framework.apatch)
                                                                         at android.app.Activity_CF.decideSpecialActivity(Activity.java:6915)
                                                                         at android.app.Activity_CF.onCreate(Activity.java:953)
                                                                         at android.support.v4.app.BaseFragmentActivityGingerbread.onCreate(BaseFragmentActivityGingerbread.java:51)
                                                                         at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:317)
                                                                         at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
                                                                         at android.app.Activity.performCreate(Activity.java:6403)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2470)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
                                                                         at android.app.ActivityThread.access$1000(ActivityThread.java:169)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5646)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:851)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:741)

**Comment by sanemars** [comment]
0.5.0这个 版本 我也遇到这个问题了。
但是 我在 找原因的过程中 自己 新建了一个工程 ，修复相同 地方的 逻辑, 新工程就不会报错。
