### ISSUE TITLE
0.3.1跑Demo可以跑起来,跑自己的项目直接crash

### ISSUE THREAD

**Issue by Eklett** [alibaba/AndFix#33]
在Application的oncreate里面执行mPatchManager = new PatchManager(this);  直接crash..
日志:
```java
java.lang.UnsatisfiedLinkError: Couldn't load andfix from loader dalvik.system.PathClassLoader
            at java.lang.Runtime.loadLibrary(Runtime.java:358)
            at java.lang.Runtime.loadLibrary(Runtime.java:348)
            at com.alipay.euler.andfix.AndFix.<clinit>(AndFix.java:37)
            at com.alipay.euler.andfix.Compat.isSupport(Compat.java:45)
            at com.alipay.euler.andfix.AndFixManager.<init>(AndFixManager.java:74)
            at com.alipay.euler.andfix.patch.PatchManager.<init>(PatchManager.java:78)
```

`No implementation found for native Lcom/alipay/euler/andfix/AndFix;.setup:(ZI)Z`
还有
```java
java.lang.UnsatisfiedLinkError: Native method not found: com.alipay.euler.andfix.AndFix.setup:(ZI)Z
            at com.alipay.euler.andfix.AndFix.setup(Native Method)
            at com.alipay.euler.andfix.AndFix.setup(AndFix.java:113)
            at com.alipay.euler.andfix.Compat.isSupport(Compat.java:45)
            at com.alipay.euler.andfix.AndFixManager.<init>(AndFixManager.java:74)
            at com.alipay.euler.andfix.patch.PatchManager.<init>(PatchManager.java:78)
```

**Comment by supern** [comment]
貌似是so没找到，检查下安装后的程序目录下是否有libandfix.so

**Comment by cokepanm** [comment]
同意楼上

**Comment by stefanlis** [comment]
change your grade version to 1.5.0

**Comment by wangrunxiang** [comment]
检查一下是否不同的指令集包下都有andfix的so
