### ISSUE TITLE
java.util.zip.ZipException: File too short to be a zip file: 0

### ISSUE THREAD

**Issue by yyfBlog** [alibaba/AndFix#331]
addPatch
                                                                  java.util.zip.ZipException: File too short to be a zip file: 0
                                                                      at java.util.zip.ZipFile.readCentralDir(ZipFile.java:388)
                                                                      at java.util.zip.ZipFile.<init>(ZipFile.java:175)
                                                                      at java.util.jar.JarFile.<init>(JarFile.java:199)
                                                                      at java.util.jar.JarFile.<init>(JarFile.java:182)
                                                                      at java.util.jar.JarFile.<init>(JarFile.java:168)
                                                                      at com.alipay.euler.andfix.patch.Patch.init(Patch.java:75)
                                                                      at com.alipay.euler.andfix.patch.Patch.<init>(Patch.java:67)
                                                                      at com.alipay.euler.andfix.patch.PatchManager.addPatch(PatchManager.java:126)
                                                                      at com.alipay.euler.andfix.patch.PatchManager.initPatchs(PatchManager.java:112)
                                                                      at com.alipay.euler.andfix.patch.PatchManager.init(PatchManager.java:105)
                                                                      at com.yyf.lifecircle.MainActivity.initAndFix(MainActivity.java:97)
                                                                      at com.yyf.lifecircle.MainActivity.onRequestPermissionsResult(MainActivity.java:88)
                                                                      at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6553)
                                                                      at android.app.Activity.dispatchActivityResult(Activity.java:6432)
                                                                      at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
                                                                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
                                                                      at android.app.ActivityThread.-wrap16(ActivityThread.java)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-20 00:57:13.306 11894-11894/com.yyf.lifecircle D/com.yyf.lifecircle.MainActivity: initAndFix: /storage/emulated/0/Dennis.apatch
02-20 00:57:13.306 11894-11894/com.yyf.lifecircle I/com.yyf.lifecircle.MainActivity: 补丁文件存在
02-20 00:57:13.306 11894-11894/com.yyf.lifecircle D/PatchManager: patch [/storage/emulated/0/Dennis.apatch] has be loaded.

**Comment by yyfBlog** [comment]
Genymotion模拟器   android6.0  运行时权限已添加，检查已经打开读写sdcard的权限，

**Comment by panq-jack** [comment]
me too

**Comment by Jeffery336699** [comment]
添加读写权限解决
