### ISSUE TITLE
用0.5.0版本就会出现崩溃

### ISSUE THREAD

**Issue by ywlm423** [alibaba/AndFix#346]
Process: com.mysoft.andfix, PID: 25382
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mysoft.andfix/com.mysoft.andfix.MainActivity}: java.lang.IllegalArgumentException: permission is null
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2306)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2364)
                                                                       at android.app.ActivityThread.access$900(ActivityThread.java:162)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:157)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5387)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                    Caused by: java.lang.IllegalArgumentException: permission is null
                                                                       at android.app.ContextImpl.checkCallingOrSelfPermission(ContextImpl.java:2179)
                                                                       at android.content.ContextWrapper.checkCallingOrSelfPermission(ContextWrapper.java:567)
                                                                       at com.mysoft.andfix.MainActivity.onCreate(MainActivity.java)
                                                                       at android.app.Activity.performCreate(Activity.java:5431)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2364) 
                                                                       at android.app.ActivityThread.access$900(ActivityThread.java:162) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:157) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5387) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081) 
                                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by ywlm423** [comment]
用0.4.0 就是正常的

**Comment by zhaolei9527** [comment]
我的也是这个错。。

**Comment by meicuihui** [comment]
现在用sophix好用些，也是阿里的
