### ISSUE TITLE
andfix exception : 

### ISSUE THREAD

**Issue by s-tree** [alibaba/AndFix#348]
java.lang.IllegalAccessError: Method 'void xxx.ui.MainActivity_CF.willJump(xxx.bean.MainTypeBean)' is inaccessible to class 'xxx.ui.MainActivity_CF' (declaration of 'xxx.MainActivity_CF' appears in /data/user/0/xxx/files/apatch/padfix-1_2_0_586-3.apatch)
                                                                           at xxx.ui.MainActivity_CF.onClick(MainActivity.java:429)
                                                                           at android.view.View.performClick(View.java:5204)
                                                                           at android.view.View$PerformClick.run(View.java:21170)
                                                                           at android.os.Handler.handleCallback(Handler.java:743)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)

![image](https://user-images.githubusercontent.com/11494163/28253493-1e042312-6ad7-11e7-8304-55b5a7a0fd0e.png)

修复代码1

![image](https://user-images.githubusercontent.com/11494163/28253675-d08320be-6ad8-11e7-9974-ce4418a14314.png)

修复代码2

![image](https://user-images.githubusercontent.com/11494163/28253484-096fdef0-6ad7-11e7-8bbe-8051d0a276dd.png)

![image](https://user-images.githubusercontent.com/11494163/28253499-3754e4d2-6ad7-11e7-9b6a-c0eb70ab4261.png)

**Comment by wyouxiong** [comment]
兄弟，这个问题你解决了吗？怎么解决的呢？

**Comment by s-tree** [comment]
并没有解决，我后来用 Sophix 了。

**Comment by wyouxiong** [comment]
谢谢

**Comment by HuskarHuang** [comment]
我也遇到同样问题，
![image](https://user-images.githubusercontent.com/17923093/50041167-5b13f700-008b-11e9-93da-fd960bb26225.png)
