### ISSUE TITLE
安卓5.1打补丁报错

### ISSUE THREAD

**Issue by fanhua1994** [alibaba/AndFix#362]
FATAL EXCEPTION: main
                                                   Process: com.hengyi.baseandroiddemo, PID: 11765
                                                   java.lang.NoSuchMethodError: No super method onCreate(Landroid/os/Bundle;)V in class Lcom/hengyi/baseandroiddemo/BaseActivity; or its super classes (declaration of 'com.hengyi.baseandroiddemo.BaseActivity' appears in /data/app/com.hengyi.baseandroiddemo-1/base.apk)
                                                       at com.hengyi.baseandroiddemo.PatchActivity_CF.onCreate(PatchActivity.java:17)
                                                       at android.app.Activity.performCreate(Activity.java:6200)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2794)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:186)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1597)
                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                       at android.os.Looper.loop(Looper.java:194)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5905)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1127)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:893)

**Comment by fanhua1994** [comment]
切换到0.4.0就好了，真的是坑。
