### ISSUE TITLE
设备名称：Galaxy S5  型号：SM-G9006V  Android版本：5.0  加载补丁崩溃

### ISSUE THREAD

**Issue by Raymond007** [alibaba/AndFix#37]
加载补丁崩溃

-----------------------------------------
设备名称：Galaxy S5  
型号：SM-G9006V  
Android版本：5.0  

AndFix引入方式为gradle：
dependencies {
    compile 'com.alipay.euler:andfix:0.3.1@aar'
}

确定不是混淆引起。
-----------------------------------------

按照文档步骤，
第一步，打一个apk包命名为1.apk，安装到设备上，运行正常；
第二步，修改代码，打一个新包，命名为2.apk；
第三步，用补丁工具apkpatch生产一个补丁文件，重命名为out.apatch放入sdcard，重新启动应用，触发补丁方法调用的时候崩溃。

**Comment by supern** [comment]
有日志吗

**Comment by Raymond007** [comment]
没有抓日志，刚建立各种模拟器测试了下，只有4.x系统是正常的，其他版本的直接崩溃

**Comment by Raymond007** [comment]
at crash-2015-09-30-19-37-05-1443613025506.log                                <
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@eaf2755
versionCode=1
BOARD=MSM8974
IS_TRANSLATION_ASSISTANT_ENABLED=false
BOOTLOADER=G9006VZNU1BOI2
TYPE=user
ID=LRX21T
TIME=1441963701000
BRAND=samsung
TAG=Build
SERIAL=81e95a61
HARDWARE=qcom
SUPPORTED_ABIS=[Ljava.lang.String;@1f4dd56a
CPU_ABI=armeabi-v7a
IS_DEBUGGABLE=false
RADIO=unknown
MANUFACTURER=samsung
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@31a320c
isOSUpgradeKK2LL=true
IS_SYSTEM_SECURE=false
TAGS=release-keys
CPU_ABI2=armeabi
UNKNOWN=unknown
USER=dpi
FINGERPRINT=samsung/kltezn/klte:5.0/LRX21T/G9006VZNU1BOI2:user/release-keys
FOTA_INFO=1441963632
HOST=SWHD4002
PRODUCT=kltezn
versionName=1.0
DISPLAY=LRX21T.G9006VZNU1BOI2
MODEL=SM-G9006V
DEVICE=klte
IS_SECURE=false
java.lang.IllegalArgumentException: Expected receiver of type com.raymond.demo.andfixdemo.MainActivity_CF, but got com.raymond.demo.andfixdemo.MainActivity
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at android.view.View$1.onClick(View.java:4216)
	at android.view.View.performClick(View.java:5155)
	at android.view.View$PerformClick.run(View.java:20747)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5835)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by Raymond007** [comment]
我的运行demo：https://github.com/Raymond007/AndFixDemo

**Comment by JuanbingTeam** [comment]
@supern  @lostoy0  这类似的问题我遇到过， 参考 #28 .

问题原因就是替换方法的时候，没替换掉clazz属性吧。
