### ISSUE TITLE
patch的修改不能修改acitivity？

### ISSUE THREAD

**Issue by 82604716** [alibaba/AndFix#42]
我发现只要新包的版本只要修改了activity 的方法 或者实现 或者 在activity新建类 打出来的patch 一运行偶读会报错 
举个例子 在更新包中实现 implements View.OnClickListener  然后打patch 一运行 直接报
java.lang.IncompatibleClassChangeError: Class 'com.euler.andfix.MainActivity' does not implement interface 'android.view.View$OnClickListener' in call to 'void android.view.View$OnClickListener.onClick(android.view.View)' (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)

手机是android 5.1  框架是否不支持 art 或者 在打新包的时候不支持修改activity的字段函数和实现集成关系？

**Comment by gdgm123** [comment]
@82604716  支持的。看代码，打新包的时候支持修改activity的字段函数和实现集成关系

**Comment by gdgm123** [comment]
@supern 
从服务器上下载补丁出现这样情况，传递时字节数组的形式,直接adb push sdcard就没有问题
java.util.zip.ZipException: Central Directory Entry signature not found; was 00140201
            at java.util.zip.ZipFile.throwZipException(ZipFile.java:427)
            at java.util.zip.ZipEntry.<init>(ZipEntry.java:360)
            at java.util.zip.ZipFile.readCentralDir(ZipFile.java:414)
            at java.util.zip.ZipFile.<init>(ZipFile.java:151)
            at java.util.zip.ZipFile.<init>(ZipFile.java:115)
            at java.util.jar.JarFile.<init>(JarFile.java:183)
            at java.util.jar.JarFile.<init>(JarFile.java:169)
            at com.alipay.euler.andfix.patch.Patch.init(Patch.java:74)
            at com.alipay.euler.andfix.patch.Patch.<init>(Patch.java:66)
            at com.alipay.euler.andfix.patch.PatchManager.addPatch(PatchManager.java:122)
            at com.alipay.euler.andfix.patch.PatchManager.addPatch(PatchManager.java:155)
            at com.babychat.activity.MyApplication$1.run(MyApplication.java:170)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

**Comment by moselin** [comment]
@zhy1905 
从服务器上下载补丁出现这样情况，传递时字节数组的形式,直接adb push sdcard就没有问题
java.util.zip.ZipException: Central Directory Entry signature not found; was 00140201
at java.util.zip.ZipFile.throwZipException(ZipFile.java:427)
at java.util.zip.ZipEntry.(ZipEntry.java:360)
at java.util.zip.ZipFile.readCentralDir(ZipFile.java:414)
大神    这个问题解决了么？如何解决的呀？
