### ISSUE TITLE
运行apkpatch报nullPointException

### ISSUE THREAD

**Issue by dengyin2000** [alibaba/AndFix#45]
很简单的一个补丁， 就是在MainActivity.onCreate中多加了一行Log.i("Andfix", "andfix is loaded."); 但是直接结果出错。

```
C:\tmp>apkpatch.bat -f C:/tmp/product-release-new.apk -t C:/tmp/product-release-bug.apk -o C:/tmp -k C:/tmp/android.keystore -p xxxxx -a xxxxx -e xxxxx
add modified Method:V  onCreate(Landroid/os/Bundle;)  in Class:Lcom/achievo/vipshop/newactivity/MainActivity;
add modified Method:Z  i(Ljava/lang/String;)  in Class:Lcom/baidu/location/t;
java.lang.NullPointerException
        at com.euler.patch.build.PatchBuilder.<init>(PatchBuilder.java:5)
        at com.euler.patch.Build.build(Build.java:74)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:72)
        at com.euler.patch.Main.main(Main.java:97)
java.lang.NullPointerException
        at com.euler.patch.build.PatchBuilder.writeMeta(PatchBuilder.java:33)
        at com.euler.patch.Build.build(Build.java:76)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:72)
        at com.euler.patch.Main.main(Main.java:97)
java.lang.NullPointerException
        at com.euler.patch.build.PatchBuilder.sealPatch(PatchBuilder.java:43)
        at com.euler.patch.Build.build(Build.java:77)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:72)
        at com.euler.patch.Main.main(Main.java:97)

```

@supern  能否帮忙定位下， 我的这个项目中有使用multi-dex

**Comment by dengyin2000** [comment]
找到问题了 原来是alias不对。

**Comment by rapeflower** [comment]
我的也报java.lang.NullPointerException

**Comment by rapeflower** [comment]
我查看我的alias填写对啦
