### ISSUE TITLE
能否Hook框架API？

### ISSUE THREAD

**Issue by gryamy** [alibaba/AndFix#52]
尝试Hook一些Framework的API，有不成功的也有成功的，还有卡死的情况。

**Comment by supern** [comment]
主要是framework的API兼容性不好保证啊

**Comment by gdgm123** [comment]
@supern 连鼎鼎大名的XPosed和Cydia Substrate到目前为止也不支持ART的Hook，你们是如何支持ART的，想了解学习学习下

**Comment by supern** [comment]
@gdgm123 我们原则上不算是hook，是方法替换

**Comment by gdgm123** [comment]
@supern 从服务器上下载补丁出现这样情况，传递时字节数组的形式,直接adb push sdcard就没有问题，下载使用开源的 async-http，求指教
java.util.zip.ZipException: Central Directory Entry signature not found; was 00140201
at java.util.zip.ZipFile.throwZipException(ZipFile.java:427)
at java.util.zip.ZipEntry.(ZipEntry.java:360)
at java.util.zip.ZipFile.readCentralDir(ZipFile.java:414)
at java.util.zip.ZipFile.(ZipFile.java:151)
at java.util.zip.ZipFile.(ZipFile.java:115)
at java.util.jar.JarFile.(JarFile.java:183)
at java.util.jar.JarFile.(JarFile.java:169)
at com.alipay.euler.andfix.patch.Patch.init(Patch.java:74)
at com.alipay.euler.andfix.patch.Patch.(Patch.java:66)

**Comment by gdgm123** [comment]
@supern  什么时候能支持eventbus？

**Comment by eaglewangy** [comment]
@gryamy fragment的生命周期hook有问题没？ @supern
