### ISSUE TITLE
apkpatch-1.0.3 无法生成补丁

### ISSUE THREAD

**Issue by lihui157** [alibaba/AndFix#53]
java.lang.NullPointerException
        at com.euler.patch.build.PatchBuilder.<init>(PatchBuilder.java:5)
        at com.euler.patch.Build.build(Build.java:74)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:72)
        at com.euler.patch.Main.main(Main.java:97)
java.lang.NullPointerException
        at com.euler.patch.build.PatchBuilder.writeMeta(PatchBuilder.java:33)
        at com.euler.patch.Build.build(Build.java:76)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:72)
        at com.euler.patch.Main.main(Main.java:97)
java.lang.NullPointerException
        at com.euler.patch.build.PatchBuilder.sealPatch(PatchBuilder.java:43)
        at com.euler.patch.Build.build(Build.java:77)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:72)
        at com.euler.patch.Main.main(Main.java:97)

**Comment by supern** [comment]
确认keystore签名信息的正确

**Comment by lihui157** [comment]
可以确认签名信息是准确的，不过签名文件是jks格式，不是keystore格式

**Comment by tonyyang123** [comment]
签名文件应该写全名，比如android.jks

**Comment by TracyZhangLei** [comment]
虽然生成了，命令行没有任何输出，解压补丁后，看到PATCH>MF中Patch-Classes为空

**Comment by 952010613** [comment]
也碰到同样问题了，1.0.3版本跟使用的是jks前面格式
apkpatch.sh -f app-release2.apk -t app-release.apk -o keystore/ –k keystore/debug.jks –p 888888 -a andfix -e 888888
提示命令使用不对，  是因为jks格式的原因吗？ 求解

**Comment by 11447416** [comment]
apkpatch.sh -f app-release2.apk -t app-release.apk -o keystore/ –k keystore/debug.jks –p 888888 -a andfix -e 888888

其中，-o keystore/ ，应该有问题，你试试写成：
apkpatch.sh -f app-release2.apk -t app-release.apk -o out.apatch –k keystore/debug.jks –p 888888 -a andfix -e 888888
