### ISSUE TITLE
android 2.3 版本运行完patch后崩溃

### ISSUE THREAD

**Issue by theroxyz** [alibaba/AndFix#62]
在os 2.3 版本的手机上兼容得不好，我测试了三部 2.3 手机，都能够运行patch，但运行结束后都会出现异常，java.lang.RuntimeException: Unable to start activity ComponentInfo{com.euler.andfix/com.euler.andfix.MainActivity}: java.lang.NullPointerException: null result when primitive expected。接着程序就挂掉了。我看了下jni文件夹下的dalvik_method_replace.cpp，应该是returnType = dvmGetBoxedReturnType_fnPtr(method);这里面的 returnType 返回的是null, 而我们期待它返回的是 PRIM_VOID，所以挂掉了。为什么会这样？有什么解决办法吗？

**Comment by theroxyz** [comment]
附上错误日志：
10-26 09:23:52.419: W/dalvikvm(27733): threadid=1: thread exiting with uncaught exception (group=0x400d0560)
10-26 09:23:52.419: E/AndroidRuntime(27733): FATAL EXCEPTION: main
10-26 09:23:52.419: E/AndroidRuntime(27733): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.euler.andfix/com.euler.andfix.MainActivity}: java.lang.NullPointerException: null result when primitive expected
10-26 09:23:52.419: E/AndroidRuntime(27733): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1650)
10-26 09:23:52.419: E/AndroidRuntime(27733): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1666)
10-26 09:23:52.419: E/AndroidRuntime(27733): 	at android.app.ActivityThread.access$1500(ActivityThread.java:117)
10-26 09:23:52.419: E/AndroidRuntime(27733): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:934)
10-26 09:23:52.419: E/AndroidRuntime(27733): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-26 09:23:52.419: E/AndroidRuntime(27733): 	at android.os.Looper.loop(Looper.java:130)
10-26 09:23:52.419: E/AndroidRuntime(27733): 	at android.app.ActivityThread.main(ActivityThread.java:3686)
10-26 09:23:52.419: E/AndroidRuntime(27733): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-26 09:23:52.419: E/AndroidRuntime(27733): 	at java.lang.reflect.Method.invoke(Method.java:507)
10-26 09:23:52.419: E/AndroidRuntime(27733): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:875)
10-26 09:23:52.419: E/AndroidRuntime(27733): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:633)
10-26 09:23:52.419: E/AndroidRuntime(27733): 	at dalvik.system.NativeStart.main(Native Method)
10-26 09:23:52.419: E/AndroidRuntime(27733): Caused by: java.lang.NullPointerException: null result when primitive expected
10-26 09:23:52.419: E/AndroidRuntime(27733): 	at com.euler.andfix.MainActivity.onCreate(Native Method)
10-26 09:23:52.419: E/AndroidRuntime(27733): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
10-26 09:23:52.419: E/AndroidRuntime(27733): 	at com.qihoo360.mobilesafe.loader.c.callActivityOnCreate(SourceFile:98)
10-26 09:23:52.419: E/AndroidRuntime(27733): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1614)
10-26 09:23:52.419: E/AndroidRuntime(27733): 	... 11 more

**Comment by gdgm123** [comment]
@theroxyz   能贴出你的关键代码吗？

**Comment by theroxyz** [comment]
Log.e(TAG, A.a("good"));
        Log.e(TAG, "" + new A().b("s1", "s2"));
        Log.e(TAG, "" + new A().getI());
        Log.i(TAG, "AndFix Success !!");
        Log.i(TAG, "AndFix Success !!");
我就是运行的Demo，加了两行输出而已。

**Comment by theroxyz** [comment]
Log.e(TAG, A.a("good"));
        Log.e(TAG, "" + new A().b("s1", "s2"));
        Log.e(TAG, "" + new A().getI());
        Log.i(TAG, "AndFix Success !!");
        Log.i(TAG, "AndFix Success !!");
我就是运行的Demo，加了两行输出而已。
