### ISSUE TITLE
 java.lang.IllegalAccessError 直接崩溃

### ISSUE THREAD

**Issue by zjf1023** [alibaba/AndFix#64]
在baseApplication中加载的apatch文件，直接崩溃, 麻烦看下，mi4手机，下面是日志:
 java.lang.IllegalAccessError: interface not accessible
            at dalvik.system.DexFile.defineClassNative(Native Method)
            at dalvik.system.DexFile.defineClass(DexFile.java:222)
            at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:215)
            at dalvik.system.DexFile.loadClass(DexFile.java:204)
            at com.alipay.euler.andfix.AndFixManager.fix(AndFixManager.java:177)
            at com.alipay.euler.andfix.patch.PatchManager.loadPatch(PatchManager.java:209)

**Comment by zjf1023** [comment]
已解决 apkpatch 替换成了1.0.3
