### ISSUE TITLE
Android4.0.3模拟器x86出现问题导致崩溃

### ISSUE THREAD

**Issue by wangmingshuo** [alibaba/AndFix#67]
android.app.SuperNotCalledException: Activity {com.euler.andfix/com.euler.andfix.MainActivity} did not call through to super.onCreate()

super.onCreate肯定是调用的，我用的就是AndroidFixDemo，其他机器正确的，但是到了x86的型号上模拟器就挂了。作者可以考虑测试一下，4.0的确存在问题。LOG错误信息如下：

10-28 11:15:00.287: D/dalvikvm(1485): Trying to load lib /data/data/com.euler.andfix/lib/libandfix.so 0xb595eb80
10-28 11:15:00.287: D/dalvikvm(1485): Added shared lib /data/data/com.euler.andfix/lib/libandfix.so 0xb595eb80
10-28 11:15:00.287: D/AndFix(1485): vm is: dalvik , apilevel is: 15
10-28 11:15:00.287: D/AndFix(1485): _Z24dvmComputeMethodArgsSizePK6Method = 0xb728cfd0
10-28 11:15:00.287: D/AndFix(1485): _Z13dvmCallMethodP6ThreadPK6MethodP6ObjectP6JValuez = 0xb72c0e70
10-28 11:15:00.287: D/AndFix(1485): _Z25dexProtoGetParameterCountPK8DexProto = 0xb72e6fc0
10-28 11:15:00.287: D/AndFix(1485): dvmAllocArrayByClass = 0xb72d25b0
10-28 11:15:00.287: D/AndFix(1485): _Z15dvmBoxPrimitive6JValueP11ClassObject = 0xb72e03c0
10-28 11:15:00.287: D/AndFix(1485): _Z21dvmFindPrimitiveClassc = 0xb72d5c80
10-28 11:15:00.287: D/AndFix(1485): dvmReleaseTrackedAlloc = 0xb72a9bf0
10-28 11:15:00.287: D/AndFix(1485): _Z17dvmCheckExceptionP6Thread = 0xb728bcc0
10-28 11:15:00.287: D/AndFix(1485): _Z15dvmGetExceptionP6Thread = 0xb728bc90
10-28 11:15:00.287: D/AndFix(1485): _Z17dvmFindArrayClassPKcP6Object = 0xb72d2290
10-28 11:15:00.287: D/AndFix(1485): _Z28dvmCreateReflectMethodObjectPK6Method = 0xb72e0fe0
10-28 11:15:00.287: D/AndFix(1485): _Z21dvmGetBoxedReturnTypePK6Method = 0xb72e01b0
10-28 11:15:00.287: D/AndFix(1485): _Z17dvmUnboxPrimitiveP6ObjectP11ClassObjectP6JValue = 0xb72e0600
10-28 11:15:00.287: D/AndFix(1485): _Z20dvmDecodeIndirectRefP6ThreadP8_jobject = 0xb728f110
10-28 11:15:00.287: D/AndFix(1485): _Z13dvmThreadSelfv = 0xb72a5c60
10-28 11:15:00.297: D/euler(1485): inited.
10-28 11:15:00.297: D/euler(1485): apatch loaded.
10-28 11:15:00.297: D/dalvikvm(1485): DexOpt: --- BEGIN 'out.apatch' (bootstrap=0) ---
10-28 11:15:00.337: D/dalvikvm(1485): DexOpt: --- END 'out.apatch' (success) ---
10-28 11:15:00.337: D/dalvikvm(1485): DEX prep '/data/data/com.euler.andfix/files/apatch/out.apatch': unzip in 0ms, rewrite 32ms
10-28 11:15:00.337: D/AndFix(1485): modify com.euler.andfix.MainActivity.TAG flag:
10-28 11:15:00.337: D/AndFix(1485): dalvik_setFieldFlag: 25 
10-28 11:15:00.337: D/AndFix(1485): dalvikMethod: onCreate
10-28 11:15:00.337: D/AndFix(1485): modify com.euler.andfix.MainActivity_CF.TAG flag:
10-28 11:15:00.337: D/AndFix(1485): dalvik_setFieldFlag: 25 
10-28 11:15:00.337: D/AndFix(1485): modify com.euler.test.A.i flag:
10-28 11:15:00.337: D/AndFix(1485): dalvik_setFieldFlag: 9 
10-28 11:15:00.337: D/AndFix(1485): modify com.euler.test.A.o flag:
10-28 11:15:00.337: D/AndFix(1485): dalvik_setFieldFlag: 9 
10-28 11:15:00.337: D/AndFix(1485): modify com.euler.test.A.s flag:
10-28 11:15:00.337: D/AndFix(1485): dalvik_setFieldFlag: 1 
10-28 11:15:00.337: D/AndFix(1485): dalvikMethod: b
10-28 11:15:00.337: D/AndFix(1485): modify com.euler.test.A_CF.i flag:
10-28 11:15:00.337: D/AndFix(1485): dalvik_setFieldFlag: 9 
10-28 11:15:00.337: D/AndFix(1485): modify com.euler.test.A_CF.o flag:
10-28 11:15:00.337: D/AndFix(1485): dalvik_setFieldFlag: 9 
10-28 11:15:00.337: D/AndFix(1485): modify com.euler.test.A_CF.s flag:
10-28 11:15:00.337: D/AndFix(1485): dalvik_setFieldFlag: 1 
10-28 11:15:00.337: D/AndFix(1485): dalvikMethod: a
10-28 11:15:00.337: D/AndFix(1485): modify com.euler.test.A_CF.i flag:
10-28 11:15:00.337: D/AndFix(1485): dalvik_setFieldFlag: 9 
10-28 11:15:00.337: D/AndFix(1485): modify com.euler.test.A_CF.o flag:
10-28 11:15:00.337: D/AndFix(1485): dalvik_setFieldFlag: 9 
10-28 11:15:00.337: D/AndFix(1485): modify com.euler.test.A_CF.s flag:
10-28 11:15:00.337: D/AndFix(1485): dalvik_setFieldFlag: 1 
10-28 11:15:00.337: D/euler(1485): apatch:/mnt/sdcard/out.apatch added.
10-28 11:15:00.337: D/AndFix(1485): dalvik_dispatcher source method: onCreate VL
10-28 11:15:00.337: D/AndFix(1485): dalvik_dispatcher target method: onCreate VL
10-28 11:15:00.337: D/AndFix(1485): dalvik_dispatcher start call->
10-28 11:15:00.337: D/AndFix(1485): boxMethodArgs object: index = 0
10-28 11:15:00.337: D/AndroidRuntime(1485): Shutting down VM
10-28 11:15:00.337: W/dalvikvm(1485): threadid=1: thread exiting with uncaught exception (group=0xb5081180)
10-28 11:15:00.337: E/AndroidRuntime(1485): FATAL EXCEPTION: main
10-28 11:15:00.337: E/AndroidRuntime(1485): android.app.SuperNotCalledException: Activity {com.euler.andfix/com.euler.andfix.MainActivity} did not call through to super.onCreate()
10-28 11:15:00.337: E/AndroidRuntime(1485): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1922)
10-28 11:15:00.337: E/AndroidRuntime(1485): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
10-28 11:15:00.337: E/AndroidRuntime(1485): 	at android.app.ActivityThread.access$600(ActivityThread.java:123)
10-28 11:15:00.337: E/AndroidRuntime(1485): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
10-28 11:15:00.337: E/AndroidRuntime(1485): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-28 11:15:00.337: E/AndroidRuntime(1485): 	at android.os.Looper.loop(Looper.java:137)
10-28 11:15:00.337: E/AndroidRuntime(1485): 	at android.app.ActivityThread.main(ActivityThread.java:4424)
10-28 11:15:00.337: E/AndroidRuntime(1485): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-28 11:15:00.337: E/AndroidRuntime(1485): 	at java.lang.reflect.Method.invoke(Method.java:511)
10-28 11:15:00.337: E/AndroidRuntime(1485): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
10-28 11:15:00.337: E/AndroidRuntime(1485): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
10-28 11:15:00.337: E/AndroidRuntime(1485): 	at dalvik.system.NativeStart.main(Native Method)
10-28 11:15:00.337: D/dalvikvm(1485): GC_CONCURRENT freed 347K, 5% free 9125K/9543K, paused 0ms+0ms
10-28 11:15:00.797: I/dalvikvm(1485): threadid=3: reacting to signal 3
10-28 11:15:00.797: I/dalvikvm(1485): Wrote stack traces to '/data/anr/traces.txt'
10-28 11:15:00.918: I/dalvikvm(1485): threadid=3: reacting to signal 3
10-28 11:15:00.918: I/dalvikvm(1485): Wrote stack traces to '/data/anr/traces.txt'

**Comment by ljluestc** [comment]
根据提供的日志，出现了android.app.SuperNotCalledException: Activity {com.euler.andfix/com.euler.andfix.MainActivity} did not call through to super.onCreate()异常。这个异常通常发生在Activity的onCreate方法中没有调用super.onCreate的情况下。

在Android中，当自定义一个Activity时，通常需要在onCreate方法中调用super.onCreate(savedInstanceState)来执行父类的初始化操作。如果没有调用父类的onCreate方法，就会抛出SuperNotCalledException异常。

在提供的日志中，有以下行：

```
10-28 11:15:00.337: E/AndroidRuntime(1485): android.app.SuperNotCalledException: Activity {com.euler.andfix/com.euler.andfix.MainActivity} did not call through to super.onCreate()
```
这表明在com.euler.andfix.MainActivity的onCreate方法中没有调用super.onCreate。

解决这个问题的方法是确保MainActivity类的onCreate方法中调用了super.onCreate(savedInstanceState)，如下所示：
```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    // Your code here
}
```

请检查MainActivity类并确保在onCreate方法中正确调用了super.onCreate。
