### ISSUE TITLE
用到MultiDex的时候找不到dex

### ISSUE THREAD

**Issue by hkinglon** [alibaba/AndFix#68]
我们项目放法太多，用到了MultiDex，用andfix的时候说是找不到dex，log如下：
pacth
10-30 14:32:11.605 14816-14816/? E/AndFixManager: java.io.IOException: unable to open DEX file
10-30 14:32:11.605 14816-14816/? E/AndFixManager:     at dalvik.system.DexFile.openDexFileNative(Native Method)
10-30 14:32:11.605 14816-14816/? E/AndFixManager:     at dalvik.system.DexFile.openDexFile(DexFile.java:304)
10-30 14:32:11.605 14816-14816/? E/AndFixManager:     at dalvik.system.DexFile.<init>(DexFile.java:115)
10-30 14:32:11.605 14816-14816/? E/AndFixManager:     at dalvik.system.DexFile.loadDex(DexFile.java:155)
10-30 14:32:11.605 14816-14816/? E/AndFixManager:     at com.alipay.euler.andfix.AndFixManager.fix(AndFixManager.java:147)
10-30 14:32:11.605 14816-14816/? E/AndFixManager:     at com.alipay.euler.andfix.patch.PatchManager.loadPatch(PatchManager.java:214)

**Comment by cokepanm** [comment]
我们也用到multidex，没有遇到这个问题呢

**Comment by hkinglon** [comment]
像这种：protected void method() {
	// A
    mGridView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
      @Override
      public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
        //  B
      }
    });
  }
在A处改是可以的，但是在B处改打出的patch就有问题，我当时改在B处了，以为是multidex问题，我又验证了下，是B处的问题，不是multidex的问题。

**Comment by pzhangleo** [comment]
@hkinglon b处修改的问题你们解决了么
