### ISSUE TITLE
java.lang.NoClassDefFoundError: android/app/AppOpsManager

### ISSUE THREAD

**Issue by lijingle1** [alibaba/AndFix#69]
我在使用AndFix过程中，程序在mPatchManager.loadPatch();的过程中会报java.lang.NoClassDefFoundError: android/app/AppOpsManager的错误。 我的apk是用ant编译出来的动态加载包

10-30 18:05:44.650 11121-11167/? D/AndFix﹕ dalvik_setFieldFlag: 9 10-30 18:05:44.650 11121-11167/? D/AndFix﹕ modify cn.ninegame.gamemanager.biz.util.OpenUserGuideUtil_CF.type flag: 10-30 18:05:44.650 11121-11167/? D/AndFix﹕ dalvik_setFieldFlag: 9 10-30 18:05:44.660 11121-11167/? W/dalvikvm﹕ Unable to match class for part: 'Landroid/app/AppOpsManager;Ljava/lang/String;IILjava/lang/String;)Ljava/lang/Integer;' 10-30 18:05:44.660 11121-11167/? I/TestRunner﹕ failed: testSkipToOnlineGamePage(cn.ninegame.gamemanager.test.base.testcase.index.FirstIndexTestCase) 10-30 18:05:44.660 11121-11167/? I/TestRunner﹕ ----- begin exception ----- 10-30 18:05:44.660 11121-11167/? I/TestRunner﹕ java.lang.NoClassDefFoundError: android/app/AppOpsManager at java.lang.Class.getDeclaredMethods(Native Method) at java.lang.Class.getDeclaredMethods(Class.java:703) at com.alipay.euler.andfix.AndFixManager.fixClass(AndFixManager.java:194) at com.alipay.euler.andfix.AndFixManager.fix(AndFixManager.java:179) at com.alipay.euler.andfix.patch.PatchManager.loadPatch(PatchManager.java:211) at cn.ninegame.gamemanager.test.common.testcase.NineGameAutoTestCase.newSetDefConfig(NineGameAutoTestCase.java:109) at cn.ninegame.gamemanager.test.common.testcase.NineGameAutoTestCase.setUp(NineGameAutoTestCase.java:85) at junit.framework.TestCase.runBare(TestCase.java:125) at junit.framework.TestResult$1.protect(TestResult.java:106) at junit.framework.TestResult.runProtected(TestResult.java:124) at junit.framework.TestResult.run(TestResult.java:109) at junit.framework.TestCase.run(TestCase.java:118) at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169) at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154) at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:545) at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1551) Caused by: java.lang.ClassNotFoundException: android.app.AppOpsManager at com.alipay.euler.andfix.AndFixManager$1.findClass(AndFixManager.java:165) at java.lang.ClassLoader.loadClass(ClassLoader.java:501) at java.lang.ClassLoader.loadClass(ClassLoader.java:461)

**Comment by lijingle1** [comment]
我大概看了一下，AppOpsManager是我们工程里使用的，报这个错的手机是低于API 19的
我们的工程是用API 21 build的，那么我用apkpatch工具制作出出来的补丁就会包含AppOpsManager
然后到了低于API 19的手机，就会报这个错。

那么这个兼容性问题该如何考虑？即高版本API制作的补丁，在低版本手机上运行

**Comment by cokepanm** [comment]
高版本制作出来的fix好的Apk，才能与旧版本apk产生补丁，如果新包为高版本，则打的补丁包括旧包里没有的类，这样应该会出现你上述错误，但是，为什么两个包用的API不一样呢？

**Comment by lijingle1** [comment]
因为我们的工程使用了API 21的Method，所以一定要用API 21编译才可以，在实际使用过程中，程序逻辑会有SDK version的判断，所以在低版本手机上APP运行正常。

因为补丁是基于API 21打出来的，在低版本手机上运行，走到加载补丁的逻辑时就会直接抛此异常。对于这种情况，不知后续AndFix框架有何方案
