### ISSUE TITLE
签名之后就错误了，不知道什么情况，自己也加上了混淆配置

### ISSUE THREAD

**Issue by wangmingshuo** [alibaba/AndFix#72]
自己混淆应该是正确的。希望作者在Demo程序中加入避免混淆的代码。我加入的混淆代码是：

-keep class * extends java.lang.annotation.Annotation
-keepclasseswithmembernames class * {
    native <methods>;
}

错误日志为：
11-06 09:08:12.877: E/AndroidRuntime(3652): java.lang.IncompatibleClassChangeError: Couldn't find com.alipay.euler.andfix.annotation.MethodReplace.clazz
11-06 09:08:12.877: E/AndroidRuntime(3652): 	at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
11-06 09:08:12.877: E/AndroidRuntime(3652): 	at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
11-06 09:08:12.877: E/AndroidRuntime(3652): 	at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:171)
11-06 09:08:12.877: E/AndroidRuntime(3652): 	at java.lang.reflect.Method.getAnnotation(Method.java:300)
11-06 09:08:12.877: E/AndroidRuntime(3652): 	at com.alipay.euler.andfix.a.a(AndFixManager.java:199)
11-06 09:08:12.877: E/AndroidRuntime(3652): 	at com.alipay.euler.andfix.a.a(AndFixManager.java:179)
11-06 09:08:12.877: E/AndroidRuntime(3652): 	at com.alipay.euler.andfix.a.b.a(PatchManager.java:238)
11-06 09:08:12.877: E/AndroidRuntime(3652): 	at com.alipay.euler.andfix.a.b.b(PatchManager.java:165)
11-06 09:08:12.877: E/AndroidRuntime(3652): 	at com.ddsc.dotbaby.app.AppContext.onCreate(AppContext.java:87)
11-06 09:08:12.877: E/AndroidRuntime(3652): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)

**Comment by MasterChenGitHub** [comment]
I add obfuscate like this,and it works.
-applymapping mapping.txt
-keep class * extends java.lang.annotation.Annotation
-keep class com.alipay.euler.**{*;}
-keepclasseswithmembernames class * {
    native <methods>;
}
