### ISSUE TITLE
加载多个apatch文件报错

### ISSUE THREAD

**Issue by qbeenslee** [alibaba/AndFix#80]
测试在Android 5.0-6.0下加载多个aptch文件, 运行被修复代码crash
同样过程在Android 4.0上并不会有问题.
**这个库是不是不支持在art runtime下进行多次修复.**
错误日志:
-------
com.demo.andfixdemo E/AndroidRuntime: FATAL EXCEPTION: main
Process: 
com.demo.andfixdemo, PID: 1832
java.lang.IllegalAccessError: Method 'void com.demo.andfixdemo.MainActivity_CF.show()' is inaccessible to class 'com.demo.andfixdemo.MainActivity_CF' (declaration of 'com.demo.andfixdemo.MainActivity_CF' appears in /data/data/com.demo.andfixdemo/files/apatch/app-release-1-4333cf2e974d886763e1b20ee2a230dc.apatch)
    at com.demo.andfixdemo.MainActivity_CF.test(MainActivity.java:45)
    at com.demo.andfixdemo.MainActivity.access$100(MainActivity.java:14)
    at com.demo.andfixdemo.MainActivity$2.onClick(MainActivity.java:29)
    at android.view.View.performClick(View.java:4780)
    at android.view.View$PerformClick.run(View.java:19866)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by fangyu286** [comment]
同问

**Comment by liericiyan** [comment]
同问

**Comment by cy20061121** [comment]
同问。。。

**Comment by jerryjobs** [comment]
同问。

**Comment by xieningtao** [comment]
同问
