### ISSUE TITLE
nexus5 6.0系统,运行demo正常,集成项目中anr.附anr traces

### ISSUE THREAD

**Issue by icemanstudy** [alibaba/AndFix#82]
----- pid 16144 at 2015-11-16 20:06:35 -----
Cmd line: com.vipshop.vsmei
Build fingerprint: 'google/hammerhead/hammerhead:6.0/MRA58K/2256973:user/release-keys'
ABI: 'arm'
Build type: optimized
Zygote loaded classes=3978 post zygote classes=1117
Intern table: 45753 strong; 174 weak
JNI: CheckJNI is on; globals=335 (plus 410 weak)
Libraries: /data/app/com.vipshop.vsmei-1/lib/arm/libVipSdkCommon.so /data/app/com.vipshop.vsmei-1/lib/arm/libandfix.so /data/app/com.vipshop.vsmei-1/lib/arm/libgifimage.so /data/app/com.vipshop.vsmei-1/lib/arm/liblocSDK6a.so /data/app/com.vipshop.vsmei-1/lib/arm/libmemchunk.so /system/lib/libandroid.so /system/lib/libcompiler_rt.so /system/lib/libjavacrypto.so /system/lib/libjnigraphics.so /system/lib/libmedia_jni.so /system/lib/libwebviewchromium_loader.so libjavacore.so (12)
Heap: 6% free, 57MB/61MB; 110160 objects
Dumping cumulative Gc timings
Start Dumping histograms for 2 iterations for partial concurrent mark sweep
ProcessMarkStack:	Sum: 5.772ms 99% C.I. 0.375us-3039.500us Avg: 962us Max: 3047us
SweepLargeObjects:	Sum: 4.690ms 99% C.I. 1.161ms-3.526ms Avg: 2.345ms Max: 3.529ms
UpdateAndMarkImageModUnionTable:	Sum: 4.282ms 99% C.I. 0.241ms-4.012ms Avg: 2.141ms Max: 4.041ms
MarkRootsCheckpoint:	Sum: 4.146ms 99% C.I. 0.432ms-1.937ms Avg: 1.036ms Max: 1.941ms
MarkConcurrentRoots:	Sum: 3.002ms 99% C.I. 4us-1665us Avg: 750.500us Max: 1665us
SweepMallocSpace:	Sum: 2.745ms 99% C.I. 4us-2167us Avg: 686.250us Max: 2195us
ReMarkRoots:	Sum: 691us 99% C.I. 309us-382us Avg: 345.500us Max: 382us
UpdateAndMarkZygoteModUnionTable:	Sum: 528us 99% C.I. 215us-313us Avg: 264us Max: 313us
ScanGrayAllocSpaceObjects:	Sum: 281us 99% C.I. 0.500us-147us Avg: 70.250us Max: 147us
ImageModUnionClearCards:	Sum: 178us 99% C.I. 38us-55us Avg: 44.500us Max: 55us
AllocSpaceClearCards:	Sum: 160us 99% C.I. 0.333us-55us Avg: 20us Max: 55us
FinishPhase:	Sum: 155us 99% C.I. 70us-85us Avg: 77.500us Max: 85us
SweepSystemWeaks:	Sum: 126us 99% C.I. 53us-73us Avg: 63us Max: 73us
(Paused)ScanGrayAllocSpaceObjects:	Sum: 87us 99% C.I. 0.250us-44us Avg: 21.750us Max: 44us
ScanGrayImageSpaceObjects:	Sum: 71us 99% C.I. 33us-38us Avg: 35.500us Max: 38us
MarkNonThreadRoots:	Sum: 70us 99% C.I. 14us-26us Avg: 17.500us Max: 26us
(Paused)ScanGrayImageSpaceObjects:	Sum: 67us 99% C.I. 30us-37us Avg: 33.500us Max: 37us
MarkAllocStackAsLive:	Sum: 65us 99% C.I. 27us-38us Avg: 32.500us Max: 38us
RevokeAllThreadLocalAllocationStacks:	Sum: 42us 99% C.I. 20us-22us Avg: 21us Max: 22us
ZygoteModUnionClearCards:	Sum: 39us 99% C.I. 7us-13us Avg: 9.750us Max: 13us
EnqueueFinalizerReferences:	Sum: 35us 99% C.I. 17us-18us Avg: 17.500us Max: 18us
MarkingPhase:	Sum: 27us 99% C.I. 13us-14us Avg: 13.500us Max: 14us
(Paused)PausePhase:	Sum: 24us 99% C.I. 10us-14us Avg: 12us Max: 14us
PreCleanCards:	Sum: 20us 99% C.I. 10us-10us Avg: 10us Max: 10us
ProcessCards:	Sum: 18us 99% C.I. 4us-5us Avg: 4.500us Max: 5us
(Paused)ScanGrayZygoteSpaceObjects:	Sum: 15us 99% C.I. 7us-8us Avg: 7.500us Max: 8us
ScanGrayZygoteSpaceObjects:	Sum: 13us 99% C.I. 6us-7us Avg: 6.500us Max: 7us
Sweep:	Sum: 12us 99% C.I. 6us-6us Avg: 6us Max: 6us
ProcessReferences:	Sum: 9us 99% C.I. 3us-6us Avg: 4.500us Max: 6us
MarkRoots:	Sum: 8us 99% C.I. 4us-4us Avg: 4us Max: 4us
RecursiveMark:	Sum: 4us 99% C.I. 2us-2us Avg: 2us Max: 2us
BindBitmaps:	Sum: 3us 99% C.I. 1us-2us Avg: 1.500us Max: 2us
InitializePhase:	Sum: 2us 99% C.I. 1us-1us Avg: 1us Max: 1us
(Paused)ProcessMarkStack:	Sum: 0 99% C.I. 0ns-0ns Avg: 0ns Max: 0ns
Done Dumping histograms 
partial concurrent mark sweep paused:	Sum: 982us 99% C.I. 452us-530us Avg: 491us Max: 530us
partial concurrent mark sweep total time: 27.424ms mean time: 13.712ms
partial concurrent mark sweep freed: 11986 objects with total size 6MB
partial concurrent mark sweep throughput: 443926/s / 228MB/s
Start Dumping histograms for 3 iterations for sticky concurrent mark sweep
FreeList:	Sum: 23.494ms 99% C.I. 4us-4205us Avg: 427.163us Max: 4687us
SweepArray:	Sum: 10.872ms 99% C.I. 0.028ms-8.990ms Avg: 3.624ms Max: 9.080ms
MarkRootsCheckpoint:	Sum: 7.522ms 99% C.I. 0.303ms-4.971ms Avg: 1.253ms Max: 5.061ms
SweepSystemWeaks:	Sum: 6.121ms 99% C.I. 0.042ms-6.010ms Avg: 2.040ms Max: 6.029ms
MarkNonThreadRoots:	Sum: 5.591ms 99% C.I. 13us-5435us Avg: 931.833us Max: 5517us
MarkConcurrentRoots:	Sum: 4.445ms 99% C.I. 3us-1622us Avg: 740.833us Max: 1622us
ProcessMarkStack:	Sum: 3.565ms 99% C.I. 0.333us-1785us Avg: 297.083us Max: 1791us
ScanGrayAllocSpaceObjects:	Sum: 3.023ms 99% C.I. 0.500us-1403us Avg: 251.916us Max: 1403us
MarkingPhase:	Sum: 2.166ms 99% C.I. 191us-1727.500us Avg: 722us Max: 1738us
AllocSpaceClearCards:	Sum: 1.987ms 99% C.I. 0.375us-1472us Avg: 165.583us Max: 1549us
ScanGrayImageSpaceObjects:	Sum: 1.246ms 99% C.I. 28us-1021.499us Avg: 207.666us Max: 1048us
ReMarkRoots:	Sum: 1.011ms 99% C.I. 300us-370us Avg: 337us Max: 370us
ImageModUnionClearCards:	Sum: 938us 99% C.I. 27us-757us Avg: 156.333us Max: 757us
(Paused)PausePhase:	Sum: 135us 99% C.I. 9us-114us Avg: 45us Max: 114us
FinishPhase:	Sum: 130us 99% C.I. 30us-55us Avg: 43.333us Max: 55us
ScanGrayZygoteSpaceObjects:	Sum: 122us 99% C.I. 5us-81us Avg: 20.333us Max: 81us
(Paused)ScanGrayAllocSpaceObjects:	Sum: 116us 99% C.I. 0.250us-45us Avg: 19.333us Max: 45us
(Paused)ScanGrayImageSpaceObjects:	Sum: 95us 99% C.I. 28us-38us Avg: 31.666us Max: 38us
EnqueueFinalizerReferences:	Sum: 90us 99% C.I. 4us-65us Avg: 30us Max: 65us
RevokeAllThreadLocalAllocationStacks:	Sum: 65us 99% C.I. 18us-24us Avg: 21.666us Max: 24us
ZygoteModUnionClearCards:	Sum: 61us 99% C.I. 6us-22us Avg: 10.166us Max: 22us
PreCleanCards:	Sum: 27us 99% C.I. 8us-10us Avg: 9us Max: 10us
ReclaimPhase:	Sum: 24us 99% C.I. 7us-10us Avg: 8us Max: 10us
(Paused)ScanGrayZygoteSpaceObjects:	Sum: 18us 99% C.I. 5us-7us Avg: 6us Max: 7us
ProcessReferences:	Sum: 17us 99% C.I. 3us-11us Avg: 5.666us Max: 11us
InitializePhase:	Sum: 14us 99% C.I. 1us-12us Avg: 4.666us Max: 12us
MarkRoots:	Sum: 12us 99% C.I. 3us-5us Avg: 4us Max: 5us
SwapStacks:	Sum: 5us 99% C.I. 1us-2us Avg: 1.666us Max: 2us
ForwardSoftReferences:	Sum: 4us 99% C.I. 1us-2us Avg: 1.333us Max: 2us
BindBitmaps:	Sum: 3us 99% C.I. 1us-1us Avg: 1us Max: 1us
FindDefaultSpaceBitmap:	Sum: 2us 99% C.I. 250ns-1000ns Avg: 666ns Max: 1000ns
(Paused)ProcessMarkStack:	Sum: 0 99% C.I. 0ns-0ns Avg: 0ns Max: 0ns
Done Dumping histograms 
sticky concurrent mark sweep paused:	Sum: 1.524ms 99% C.I. 418us-610us Avg: 508us Max: 610us
sticky concurrent mark sweep total time: 73.090ms mean time: 24.363ms
sticky concurrent mark sweep freed: 51942 objects with total size 4MB
sticky concurrent mark sweep throughput: 711534/s / 60MB/s
Total time spent in GC: 100.514ms
Mean GC size throughput: 50MB/s
Mean GC object throughput: 635842 objects/s
Total number of allocations 174071
Total bytes allocated 62MB
Total bytes freed 5MB
Free memory 3MB
Free memory until GC 3MB
Free memory until OOME 454MB
Total memory 61MB
Max memory 512MB
Zygote space size 1312KB
Total mutator paused time: 2.506ms
Total time waiting for GC to complete: 8.646us
Total GC count: 5
Total GC time: 100.514ms
Total blocking GC count: 0
Total blocking GC time: 0

suspend all histogram:	Sum: 17.629ms 99% C.I. 2us-255.776us Avg: 72.847us Max: 11111us
DALVIK THREADS (34):
"Signal Catcher" daemon prio=5 tid=2 Runnable
  | group="system" sCount=0 dsCount=0 obj=0x12ca50a0 self=0xaee9a000
  | sysTid=16149 nice=0 cgrp=default sched=0/0 handle=0xb44ad930
  | state=R schedstat=( 2895832 1031303 4 ) utm=0 stm=0 core=1 HZ=100
  | stack=0xb43b1000-0xb43b3000 stackSize=1014KB
  | held mutexes= "mutator lock"(shared held)
  native: #00 pc 00370aa9  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::ArtMethod*, void*)+160)
  native: #01 pc 003503b7  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+150)
  native: #02 pc 0035a01b  /system/lib/libart.so (art::DumpCheckpoint::Run(art::Thread*)+442)
  native: #03 pc 0035abd9  /system/lib/libart.so (art::ThreadList::RunCheckpoint(art::Closure*)+212)
  native: #04 pc 0035b107  /system/lib/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+142)
  native: #05 pc 0035b817  /system/lib/libart.so (art::ThreadList::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+334)
  native: #06 pc 00333c17  /system/lib/libart.so (art::Runtime::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+74)
  native: #07 pc 0033af7d  /system/lib/libart.so (art::SignalCatcher::HandleSigQuit()+928)
  native: #08 pc 0033b861  /system/lib/libart.so (art::SignalCatcher::Run(void*)+340)
  native: #09 pc 0003f3e7  /system/lib/libc.so (__pthread_start(void*)+30)
  native: #10 pc 00019b43  /system/lib/libc.so (__start_thread+6)
  (no managed stack frames)

"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x7310c2a0 self=0xb4df6a00
  | sysTid=16144 nice=0 cgrp=default sched=0/0 handle=0xb6fceb34
  | state=S schedstat=( 860664512 271374341 1512 ) utm=70 stm=16 core=1 HZ=100
  | stack=0xbe011000-0xbe013000 stackSize=8MB
  | held mutexes=
  at com.vipshop.vsmei.circle.CircleSpecialListManager$2.callback(CircleSpecialListManager.java:113)
  - waiting on <0x0528aaca> (a java.lang.Class<com.vipshop.vsmei.circle.control.CircleSpecialListController_CF>)
  at com.vipshop.vsmei.circle.CircleSpecialListManager$2.callback(CircleSpecialListManager.java:108)
  at com.androidquery.callback.AbstractAjaxCallback.callback(AbstractAjaxCallback.java:603)
  at com.androidquery.callback.AbstractAjaxCallback.afterWork(AbstractAjaxCallback.java:1402)
  at com.androidquery.callback.AbstractAjaxCallback.run(AbstractAjaxCallback.java:1085)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

"JDWP" daemon prio=5 tid=3 WaitingInMainDebuggerLoop
  | group="system" sCount=1 dsCount=0 obj=0x12ca80a0 self=0xacc51f00
  | sysTid=16150 nice=0 cgrp=default sched=0/0 handle=0xb43ae930
  | state=S schedstat=( 391782501 151721508 331 ) utm=35 stm=4 core=0 HZ=100
  | stack=0xb42b2000-0xb42b4000 stackSize=1014KB
  | held mutexes=
  native: #00 pc 000415d4  /system/lib/libc.so (__pselect6+20)
  native: #01 pc 0001bcb5  /system/lib/libc.so (select+60)
  native: #02 pc 00400f7b  /system/lib/libart.so (art::JDWP::JdwpAdbState::ProcessIncoming()+218)
  native: #03 pc 00266e1f  /system/lib/libart.so (art::JDWP::JdwpState::Run()+314)
  native: #04 pc 00267c9d  /system/lib/libart.so (art::JDWP::StartJdwpThread(void*)+16)
  native: #05 pc 0003f3e7  /system/lib/libc.so (__pthread_start(void*)+30)
  native: #06 pc 00019b43  /system/lib/libc.so (__start_thread+6)
  (no managed stack frames)

"HeapTaskDaemon" daemon prio=5 tid=4 Blocked
  | group="system" sCount=1 dsCount=0 obj=0x12ca43a0 self=0xacc55100
  | sysTid=16154 nice=0 cgrp=default sched=0/0 handle=0xb3f95930
  | state=S schedstat=( 64636965 54656883 252 ) utm=4 stm=2 core=0 HZ=100
  | stack=0xb3e93000-0xb3e95000 stackSize=1038KB
  | held mutexes=
  native: #00 pc 000175e4  /system/lib/libc.so (syscall+28)
  native: #01 pc 000f6b49  /system/lib/libart.so (art::ConditionVariable::Wait(art::Thread*)+96)
  native: #02 pc 001d73cd  /system/lib/libart.so (art::gc::TaskProcessor::GetTask(art::Thread*)+104)
  native: #03 pc 001d7901  /system/lib/libart.so (art::gc::TaskProcessor::RunAllTasks(art::Thread*)+72)
  native: #04 pc 0000037f  /data/dalvik-cache/arm/system@framework@boot.oat (Java_dalvik_system_VMRuntime_runHeapTasks__+74)
  at dalvik.system.VMRuntime.runHeapTasks(Native method)
  - waiting to lock an unknown object
  at java.lang.Daemons$HeapTaskDaemon.run(Daemons.java:355)
  at java.lang.Thread.run(Thread.java:818)

"FinalizerDaemon" daemon prio=5 tid=5 Waiting
  | group="system" sCount=1 dsCount=0 obj=0x12ca42e0 self=0xacc54700
  | sysTid=16152 nice=0 cgrp=default sched=0/0 handle=0xb41a3930
  | state=S schedstat=( 5139584 2792239 18 ) utm=0 stm=0 core=1 HZ=100
  | stack=0xb40a1000-0xb40a3000 stackSize=1038KB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x0896743b> (a java.lang.ref.ReferenceQueue)
  at java.lang.Object.wait(Object.java:423)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
  - locked <0x0896743b> (a java.lang.ref.ReferenceQueue)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
  at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
  at java.lang.Thread.run(Thread.java:818)

"FinalizerWatchdogDaemon" daemon prio=5 tid=6 Waiting
  | group="system" sCount=1 dsCount=0 obj=0x12ca4340 self=0xacc54c00
  | sysTid=16153 nice=0 cgrp=default sched=0/0 handle=0xb409c930
  | state=S schedstat=( 726147 16086248 11 ) utm=0 stm=0 core=0 HZ=100
  | stack=0xb3f9a000-0xb3f9c000 stackSize=1038KB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x001ba758> (a java.lang.Daemons$FinalizerWatchdogDaemon)
  at java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:255)
  - locked <0x001ba758> (a java.lang.Daemons$FinalizerWatchdogDaemon)
  at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:227)
  at java.lang.Thread.run(Thread.java:818)

"ReferenceQueueDaemon" daemon prio=5 tid=7 Waiting
  | group="system" sCount=1 dsCount=0 obj=0x12ca4280 self=0xacc54200
  | sysTid=16151 nice=0 cgrp=default sched=0/0 handle=0xb42aa930
  | state=S schedstat=( 1443648 13755470 31 ) utm=0 stm=0 core=1 HZ=100
  | stack=0xb41a8000-0xb41aa000 stackSize=1038KB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x0ed340b1> (a java.lang.Class<java.lang.ref.ReferenceQueue>)
  at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:147)
  - locked <0x0ed340b1> (a java.lang.Class<java.lang.ref.ReferenceQueue>)
  at java.lang.Thread.run(Thread.java:818)

"Binder_1" prio=5 tid=8 Native
  | group="main" sCount=1 dsCount=0 obj=0x12cc80a0 self=0xaee9b400
  | sysTid=16155 nice=0 cgrp=default sched=0/0 handle=0xb3d86930
  | state=S schedstat=( 16583485 48850161 117 ) utm=0 stm=1 core=0 HZ=100
  | stack=0xb3c8a000-0xb3c8c000 stackSize=1014KB
  | held mutexes=
  native: #00 pc 00041cf4  /system/lib/libc.so (__ioctl+8)
  native: #01 pc 000473c5  /system/lib/libc.so (ioctl+14)
  native: #02 pc 0001e7cd  /system/lib/libbinder.so (android::IPCThreadState::talkWithDriver(bool)+132)
  native: #03 pc 0001ecaf  /system/lib/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+6)
  native: #04 pc 0001ed4d  /system/lib/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+48)
  native: #05 pc 00023639  /system/lib/libbinder.so (???)
  native: #06 pc 0001006d  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+112)
  native: #07 pc 0005ecd3  /system/lib/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+70)
  native: #08 pc 0003f3e7  /system/lib/libc.so (__pthread_start(void*)+30)
  native: #09 pc 00019b43  /system/lib/libc.so (__start_thread+6)
  (no managed stack frames)

"Binder_2" prio=5 tid=9 Native
  | group="main" sCount=1 dsCount=0 obj=0x12cec0a0 self=0xacc5bf00
  | sysTid=16156 nice=0 cgrp=default sched=0/0 handle=0xb3c82930
  | state=S schedstat=( 14630214 29801823 115 ) utm=1 stm=0 core=0 HZ=100
  | stack=0xb3b86000-0xb3b88000 stackSize=1014KB
  | held mutexes=
  native: #00 pc 00041cf4  /system/lib/libc.so (__ioctl+8)
  native: #01 pc 000473c5  /system/lib/libc.so (ioctl+14)
  native: #02 pc 0001e7cd  /system/lib/libbinder.so (android::IPCThreadState::talkWithDriver(bool)+132)
  native: #03 pc 0001ecaf  /system/lib/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+6)
  native: #04 pc 0001ed4d  /system/lib/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+48)
  native: #05 pc 00023639  /system/lib/libbinder.so (???)
  native: #06 pc 0001006d  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+112)
  native: #07 pc 0005ecd3  /system/lib/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+70)
  native: #08 pc 0003f3e7  /system/lib/libc.so (__pthread_start(void*)+30)
  native: #09 pc 00019b43  /system/lib/libc.so (__start_thread+6)
  (no managed stack frames)

**Comment by THEONE10211024** [comment]
红米note2上也有~~~

**Comment by landryshuai** [comment]
@THEONE10211024  是不是修复的是静态方法？

**Comment by augusting52** [comment]
华为麦芒5也有这个问题？请问解决了吗？
