### ISSUE TITLE
can,t modified Field

### ISSUE THREAD

**Issue by ouyangfeng** [alibaba/AndFix#87]
java.lang.RuntimeException: can,t modified Field:FLAVOR(Ljava/lang/String;), in class :Lcom/euler/andfix/BuildConfig;
	at com.euler.patch.diff.DiffInfo.addModifiedFields(DiffInfo.java:88)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:125)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:101)
	at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:95)
	at com.euler.patch.diff.DexDiffer.diff(DexDiffer.java:32)
	at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:68)
	at com.euler.patch.Main.main(Main.java:97)

**Comment by bravolover520** [comment]
I have the same problem.

java.lang.RuntimeException: can,t modified Field:VERSION_NAME(Ljava/lang/String;
), in class :Lcom/zhiqu/ynapp/BuildConfig;
        at com.euler.patch.diff.DiffInfo.addModifiedFields(DiffInfo.java:88)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:125)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:101)
        at com.euler.patch.diff.DexDiffer.compareField(DexDiffer.java:95)
        at com.euler.patch.diff.DexDiffer.diff(DexDiffer.java:32)
        at com.euler.patch.ApkPatch.doPatch(ApkPatch.java:68)
        at com.euler.patch.Main.main(Main.java:97)

**Comment by chundongwang** [comment]
用JD-GUI打开apkpatch-1.0.3.jar可以看到如下代码，说明至少从apkpatch来看成员变量的修改是不支持的。
```
  public void addModifiedFields(DexBackedField field)
  {
    this.modifiedFields.add(field);
    throw new RuntimeException("can,t modified Field:" + 
      field.getName() + "(" + field.getType() + "), " + "in class :" + 
      field.getDefiningClass());
  }
```

**Comment by busymilk** [comment]
那最后怎么解决呢，现在没法生成补丁文件啊

**Comment by chundongwang** [comment]
另外一个帖子提到用jboss的javassist来改bytecode，我自己实现了一次能够用。我因为需要command line所以没办法用那个帖主的gui工具。你可以试试他的工具，原理应该是一样的。

**Comment by busymilk** [comment]
ok

**Comment by hlllmr1314** [comment]
局限性
不支持YunOS
无法添加新类和新的字段
需要使用加固前的apk制作补丁，但是补丁文件很容易被反编译，也就是修改过的类源码容易泄露。
使用加固平台可能会使热补丁功能失效（看到有人在360加固提了这个问题，自己还未验证）。

你这个最好升级version了
