### ISSUE TITLE
apatch命令报错

### ISSUE THREAD

**Issue by rjliulei** [alibaba/AndFix#91]
windows上合并命令报错，java.io.FileNotFoundException: \merge.dex (系统找不到指定的文件。)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)

**Comment by liericiyan** [comment]
不知道你是不是一个版本多次修复bug的情况，我用这种方式处理的：
  mPatchManager = new PatchManager(this);
        mPatchManager.init("1.0");
        Log.d(TAG, "inited.");
        mPatchManager.removeAllPatch();
        // load patch
        mPatchManager.loadPatch();
        Log.d(TAG, "apatch loaded.");

        // add patch at runtime
        try {
            // .apatch file path
            String patchFileString = Environment.getExternalStorageDirectory()
                    .getAbsolutePath() + APATCH_PATH;
            mPatchManager.addPatch(patchFileString);
            Log.d(TAG, "apatch:" + patchFileString + " added.");
        } catch (IOException e) {
            Log.e(TAG, "", e);
        }
        Log.e(TAG, A.a("good"));
        Log.e(TAG, "" + new A().b("s1", "s2"));
