### ISSUE TITLE
Android 5.x 上无法装载（AndFix.setup）

### ISSUE THREAD

**Issue by DoubleAngle** [alibaba/AndFix#93]
如题，我在Moto X Play、 Moto X Pro、魅族上都报错，错误如下：
java.lang.UnsatisfiedLinkError: No implementation found for boolean com.alipay.euler.andfix.AndFix.setup(boolean, int) 
(tried Java_com_alipay_euler_andfix_AndFix_setup and Java_com_alipay_euler_andfix_AndFix_setup__ZI)。
 运行DEMO没有问题，但是放在自己的项目中有问题

**Comment by JChord** [comment]
cpu指令集是arm64-v8a的，andfix少了这个so文件。

**Comment by ytrjp** [comment]
是的，我这边跑demo也没问题，一放到自己的项目就跪了。
11-26 18:01:42.278 6682-6682/com.zhtx.zhtxghs E/AndFix: loadLibrary
                                                        java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.zhtx.zhtxghs-2/base.apk"],nativeLibraryDirectories=[/data/app/com.zhtx.zhtxghs-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libandfix.so"
                                                            at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                            at java.lang.Runtime.loadLibrary(Runtime.java:352)
                                                            at com.alipay.euler.andfix.AndFix.<clinit>(AndFix.java:37)
                                                            at com.alipay.euler.andfix.AndFix.setup(AndFix.java)
                                                            at com.alipay.euler.andfix.Compat.isSupport(Compat.java:45)
                                                            at com.alipay.euler.andfix.AndFixManager.<init>(AndFixManager.java:74)
                                                            at com.alipay.euler.andfix.patch.PatchManager.<init>(PatchManager.java:77)
                                                            at com.zhtx.zhtxghs.softapplication.SoftApplication.onCreate(SoftApplication.java:84)
                                                            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1034)
                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4605)
                                                            at android.app.ActivityThread.access$1500(ActivityThread.java:148)
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                            at android.os.Looper.loop(Looper.java:135)
                                                            at android.app.ActivityThread.main(ActivityThread.java:5312)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
11-26 18:01:42.281 6682-6682/com.zhtx.zhtxghs E/art: No implementation found for boolean com.alipay.euler.andfix.AndFix.setup(boolean, int) (tried Java_com_alipay_euler_andfix_AndFix_setup and Java_com_alipay_euler_andfix_AndFix_setup__ZI)
11-26 18:01:45.672 6682-6682/com.zhtx.zhtxghs D/AndroidRuntime: Shutting down VM
11-26 18:01:49.932 6682-6682/com.zhtx.zhtxghs E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.zhtx.zhtxghs, PID: 6682
                                                                java.lang.UnsatisfiedLinkError: No implementation found for boolean com.alipay.euler.andfix.AndFix.setup(boolean, int) (tried Java_com_alipay_euler_andfix_AndFix_setup and Java_com_alipay_euler_andfix_AndFix_setup__ZI)
                                                                    at com.alipay.euler.andfix.AndFix.setup(Native Method)
                                                                    at com.alipay.euler.andfix.AndFix.setup(AndFix.java:113)
                                                                    at com.alipay.euler.andfix.Compat.isSupport(Compat.java:45)
                                                                    at com.alipay.euler.andfix.AndFixManager.<init>(AndFixManager.java:74)
                                                                    at com.alipay.euler.andfix.patch.PatchManager.<init>(PatchManager.java:77)
                                                                    at com.zhtx.zhtxghs.softapplication.SoftApplication.onCreate(SoftApplication.java:84)
                                                                    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1034)
                                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4605)
                                                                    at android.app.ActivityThread.access$1500(ActivityThread.java:148)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5312)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by LiaoZhuo** [comment]
请问楼上各位是如何混淆的，本人混淆后就报类找不到的错误，而且也配置了第一次的mapping.txt到第二次的混淆文件-applymapping中。

**Comment by LiaoZhuo** [comment]
混淆配置如下：
`<-keep class * extends java.lang.annotation.Annotation
-keepclasseswithmembernames class * {
    native <methods>;
}
-keep class com.alipay.euler.andfix.annotation.MethodReplace { *; }
-keep class com.alipay.euler.** {*;}
-printmapping build/outputs/mapping/debug/mapping.txt
-applymapping mapping1.txt>`

**Comment by DoubleAngle** [comment]
我测试了很多机型，实在无奈，没有好的解决方案，现在用的是nuwa

**Comment by THEONE10211024** [comment]
@DoubleAngle nuwa怎么样？适配所有CPU和Android版本么？

**Comment by THEONE10211024** [comment]
@ytrjp 你的问题解决了吗？

**Comment by birdman2005** [comment]
估计大家需要重新编译so文件了。cpu是armv7的要编译armebia-v7

**Comment by DoubleAngle** [comment]
@THEONE10211024  Nuwa可以，最近又查出一个Nuwa的一个BUG，提交给作者了，作者近期会改，Nuwa我已经集成了。

**Comment by LuoboDcom** [comment]
@DoubleAngle 我用Nuwa遇到Android_Home这个问题，作者还没改，郁闷

**Comment by ytrjp** [comment]
@THEONE10211024 还木有

**Comment by chundongwang** [comment]
我觉得楼上这些可能也跟没有设置jniLibs有关系，记得在app/build.gradle里把jniLibs指向你存放这些so文件的目录

**Comment by lingruizhong** [comment]
加载so文件的class文件，它的包名必须是原生demo里的包名，不能自己给它随便设置包名，希望能对你们有帮助
