### ISSUE TITLE
so loadLibray is error

### ISSUE THREAD

**Issue by ytrjp** [alibaba/AndFix#95]
loadLibrary
                                                          java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.zhtx.zhtxghs-1/base.apk"],nativeLibraryDirectories=[/data/app/com.zhtx.zhtxghs-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libandfix.so"
                                                              at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                              at java.lang.Runtime.loadLibrary(Runtime.java:352)
                                                              at com.alipay.euler.andfix.AndFix.<clinit>(AndFix.java:37)
                                                              at com.alipay.euler.andfix.Compat.isSupport(Compat.java:45)
                                                              at com.alipay.euler.andfix.AndFixManager.<init>(AndFixManager.java:74)
                                                              at com.alipay.euler.andfix.patch.PatchManager.<init>(PatchManager.java:77)
                                                              at com.alipay.euler.andfix.PatchUtils.initPatchManager(PatchUtils.java:13)
                                                              at com.zhtx.zhtxghs.softapplication.SoftApplication.onCreate(SoftApplication.java:85)
                                                              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1034)
                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4605)
                                                              at android.app.ActivityThread.access$1500(ActivityThread.java:148)
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                              at android.os.Looper.loop(Looper.java:135)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5312)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
11-27 16:33:43.437 27491-27491/com.zhtx.zhtxghs E/art: No implementation found for boolean com.alipay.euler.andfix.AndFix.setup(boolean, int) (tried Java_com_alipay_euler_andfix_AndFix_setup and Java_com_alipay

**Comment by birdman2005** [comment]
同样的问题，不知道是不是so对应的版本不一样，身边两个root的手机都没有。apk解压之后有这个so文件啊，nexus5测试的。换了几个别的手机试了一下也不行

**Comment by birdman2005** [comment]
刚才看了一下，应该是cpu的问题，大部分cpu是arm v7的，这个默认的库不是，需要自己编译

**Comment by sfsheng0322** [comment]
怎么编译啊，应该如何编译出arm v7的动态库啊？@birdman2005

**Comment by sunchenliang** [comment]
我也遇到这个问题，在写Demo的时候有没问题，移到自己项目的时候就有这个问题，我用的是nexus 5，应该不是.so版本问题，有人有解决这个问题吗？
